/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AsyncFormVideoBotsRequestTranslationModel = "google" | "ghana_nlp";

export const AsyncFormVideoBotsRequestTranslationModel = {
    Google: "google",
    GhanaNlp: "ghana_nlp",
} as const;
