/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateStreamRequestLipsyncModel = "Wav2Lip" | "SadTalker";

export const CreateStreamRequestLipsyncModel = {
    Wav2Lip: "Wav2Lip",
    SadTalker: "SadTalker",
} as const;
