/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VideoBotsStreamCreateRequestOpenaiTtsModel = "tts_1" | "tts_1_hd";

export const VideoBotsStreamCreateRequestOpenaiTtsModel = {
    Tts1: "tts_1",
    Tts1Hd: "tts_1_hd",
} as const;
