/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../../index";

export type VideoBotsStreamResponse =
    | Gooey.ConversationStart
    | Gooey.RunStart
    | Gooey.MessagePart
    | Gooey.FinalResponse
    | Gooey.StreamError;
