/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VideoBotsStreamCreateRequestLipsyncModel = "Wav2Lip" | "SadTalker";

export const VideoBotsStreamCreateRequestLipsyncModel = {
    Wav2Lip: "Wav2Lip",
    SadTalker: "SadTalker",
} as const;
