/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as Gooey from "../index";

export class TooManyRequestsError extends errors.GooeyError {
    constructor(body: Gooey.GenericErrorResponse) {
        super({
            message: "TooManyRequestsError",
            statusCode: 429,
            body: body,
        });
        Object.setPrototypeOf(this, TooManyRequestsError.prototype);
    }
}
