/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class GooeyTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, GooeyTimeoutError.prototype);
    }
}
