/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const Img2ImgPageRequestSelectedModel: core.serialization.Schema<
    serializers.Img2ImgPageRequestSelectedModel.Raw,
    Gooey.Img2ImgPageRequestSelectedModel
> = core.serialization.enum_([
    "dream_shaper",
    "dreamlike_2",
    "sd_2",
    "sd_1_5",
    "dall_e",
    "instruct_pix2pix",
    "openjourney_2",
    "openjourney",
    "analog_diffusion",
    "protogen_5_3",
    "jack_qiao",
    "rodent_diffusion_1_5",
]);

export declare namespace Img2ImgPageRequestSelectedModel {
    type Raw =
        | "dream_shaper"
        | "dreamlike_2"
        | "sd_2"
        | "sd_1_5"
        | "dall_e"
        | "instruct_pix2pix"
        | "openjourney_2"
        | "openjourney"
        | "analog_diffusion"
        | "protogen_5_3"
        | "jack_qiao"
        | "rodent_diffusion_1_5";
}
