/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const CreateStreamRequestTranslationModel: core.serialization.Schema<
    serializers.CreateStreamRequestTranslationModel.Raw,
    Gooey.CreateStreamRequestTranslationModel
> = core.serialization.enum_(["google", "ghana_nlp"]);

export declare namespace CreateStreamRequestTranslationModel {
    type Raw = "google" | "ghana_nlp";
}
