/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const CreateStreamRequestTtsProvider: core.serialization.Schema<
    serializers.CreateStreamRequestTtsProvider.Raw,
    Gooey.CreateStreamRequestTtsProvider
> = core.serialization.enum_(["GOOGLE_TTS", "ELEVEN_LABS", "UBERDUCK", "BARK", "AZURE_TTS", "OPEN_AI"]);

export declare namespace CreateStreamRequestTtsProvider {
    type Raw = "GOOGLE_TTS" | "ELEVEN_LABS" | "UBERDUCK" | "BARK" | "AZURE_TTS" | "OPEN_AI";
}
