/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";
import { ConversationStart } from "../../../types/ConversationStart";
import { RunStart } from "../../../types/RunStart";
import { MessagePart } from "../../../types/MessagePart";
import { FinalResponse } from "../../../types/FinalResponse";
import { StreamError } from "../../../types/StreamError";

export const VideoBotsStreamResponse: core.serialization.Schema<
    serializers.VideoBotsStreamResponse.Raw,
    Gooey.VideoBotsStreamResponse
> = core.serialization.undiscriminatedUnion([ConversationStart, RunStart, MessagePart, FinalResponse, StreamError]);

export declare namespace VideoBotsStreamResponse {
    type Raw = ConversationStart.Raw | RunStart.Raw | MessagePart.Raw | FinalResponse.Raw | StreamError.Raw;
}
