/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const VideoBotsStreamCreateRequestAsrModel: core.serialization.Schema<
    serializers.VideoBotsStreamCreateRequestAsrModel.Raw,
    Gooey.VideoBotsStreamCreateRequestAsrModel
> = core.serialization.enum_([
    "whisper_large_v2",
    "whisper_large_v3",
    "whisper_hindi_large_v2",
    "whisper_telugu_large_v2",
    "nemo_english",
    "nemo_hindi",
    "vakyansh_bhojpuri",
    "gcp_v1",
    "usm",
    "deepgram",
    "azure",
    "seamless_m4t_v2",
    "mms_1b_all",
    "seamless_m4t",
]);

export declare namespace VideoBotsStreamCreateRequestAsrModel {
    type Raw =
        | "whisper_large_v2"
        | "whisper_large_v3"
        | "whisper_hindi_large_v2"
        | "whisper_telugu_large_v2"
        | "nemo_english"
        | "nemo_hindi"
        | "vakyansh_bhojpuri"
        | "gcp_v1"
        | "usm"
        | "deepgram"
        | "azure"
        | "seamless_m4t_v2"
        | "mms_1b_all"
        | "seamless_m4t";
}
