/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const VideoBotsStreamCreateRequestLipsyncModel: core.serialization.Schema<
    serializers.VideoBotsStreamCreateRequestLipsyncModel.Raw,
    Gooey.VideoBotsStreamCreateRequestLipsyncModel
> = core.serialization.enum_(["Wav2Lip", "SadTalker"]);

export declare namespace VideoBotsStreamCreateRequestLipsyncModel {
    type Raw = "Wav2Lip" | "SadTalker";
}
