/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const AsrPageRequestOutputFormat: core.serialization.Schema<
    serializers.AsrPageRequestOutputFormat.Raw,
    Gooey.AsrPageRequestOutputFormat
> = core.serialization.enum_(["text", "json", "srt", "vtt"]);

export declare namespace AsrPageRequestOutputFormat {
    type Raw = "text" | "json" | "srt" | "vtt";
}
