/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as Gooey from "../../../api/index";
import * as core from "../../../core";
import { RunSettings } from "../../types/RunSettings";

export const FunctionsPageRequest: core.serialization.Schema<
    serializers.FunctionsPageRequest.Raw,
    Omit<Gooey.FunctionsPageRequest, "exampleId">
> = core.serialization.object({
    code: core.serialization.string().optional(),
    variables: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    settings: RunSettings.optional(),
});

export declare namespace FunctionsPageRequest {
    interface Raw {
        code?: string | null;
        variables?: Record<string, unknown> | null;
        settings?: RunSettings.Raw | null;
    }
}
