/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Gooey from "../../../../../api/index";
import * as core from "../../../../../core";
import { RecipeFunction } from "../../../../types/RecipeFunction";
import { ObjectInpaintingPageRequestSelectedModel } from "../../types/ObjectInpaintingPageRequestSelectedModel";
import { RunSettings } from "../../../../types/RunSettings";

export const ObjectInpaintingPageRequest: core.serialization.Schema<
    serializers.ObjectInpaintingPageRequest.Raw,
    Omit<Gooey.ObjectInpaintingPageRequest, "exampleId">
> = core.serialization.object({
    functions: core.serialization.list(RecipeFunction).optional(),
    variables: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    inputImage: core.serialization.property("input_image", core.serialization.string()),
    textPrompt: core.serialization.property("text_prompt", core.serialization.string()),
    objScale: core.serialization.property("obj_scale", core.serialization.number().optional()),
    objPosX: core.serialization.property("obj_pos_x", core.serialization.number().optional()),
    objPosY: core.serialization.property("obj_pos_y", core.serialization.number().optional()),
    maskThreshold: core.serialization.property("mask_threshold", core.serialization.number().optional()),
    selectedModel: core.serialization.property("selected_model", ObjectInpaintingPageRequestSelectedModel.optional()),
    negativePrompt: core.serialization.property("negative_prompt", core.serialization.string().optional()),
    numOutputs: core.serialization.property("num_outputs", core.serialization.number().optional()),
    quality: core.serialization.number().optional(),
    outputWidth: core.serialization.property("output_width", core.serialization.number().optional()),
    outputHeight: core.serialization.property("output_height", core.serialization.number().optional()),
    guidanceScale: core.serialization.property("guidance_scale", core.serialization.number().optional()),
    sd2Upscaling: core.serialization.property("sd_2_upscaling", core.serialization.boolean().optional()),
    seed: core.serialization.number().optional(),
    settings: RunSettings.optional(),
});

export declare namespace ObjectInpaintingPageRequest {
    interface Raw {
        functions?: RecipeFunction.Raw[] | null;
        variables?: Record<string, unknown> | null;
        input_image: string;
        text_prompt: string;
        obj_scale?: number | null;
        obj_pos_x?: number | null;
        obj_pos_y?: number | null;
        mask_threshold?: number | null;
        selected_model?: ObjectInpaintingPageRequestSelectedModel.Raw | null;
        negative_prompt?: string | null;
        num_outputs?: number | null;
        quality?: number | null;
        output_width?: number | null;
        output_height?: number | null;
        guidance_scale?: number | null;
        sd_2_upscaling?: boolean | null;
        seed?: number | null;
        settings?: RunSettings.Raw | null;
    }
}
