/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AggFunctionResultFunction =
    | "mean"
    | "median"
    | "min"
    | "max"
    | "sum"
    | "cumsum"
    | "prod"
    | "cumprod"
    | "std"
    | "var"
    | "first"
    | "last"
    | "count"
    | "cumcount"
    | "nunique"
    | "rank";

export const AggFunctionResultFunction = {
    Mean: "mean",
    Median: "median",
    Min: "min",
    Max: "max",
    Sum: "sum",
    Cumsum: "cumsum",
    Prod: "prod",
    Cumprod: "cumprod",
    Std: "std",
    Var: "var",
    First: "first",
    Last: "last",
    Count: "count",
    Cumcount: "cumcount",
    Nunique: "nunique",
    Rank: "rank",
} as const;
