/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface AggFunctionResult {
    column: string;
    function: Gooey.AggFunctionResultFunction;
    count: number;
    value: number;
}
