/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface AsrPageRequest {
    functions?: Gooey.AsrPageRequestFunctionsItem[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    documents: string[];
    selectedModel?: Gooey.AsrPageRequestSelectedModel;
    language?: string;
    translationModel?: Gooey.AsrPageRequestTranslationModel;
    outputFormat?: Gooey.AsrPageRequestOutputFormat;
    /** use `translation_model` & `translation_target` instead. */
    googleTranslateTarget?: string;
    translationSource?: string;
    translationTarget?: string;
    glossaryDocument?: string;
    settings?: Gooey.RunSettings;
}
