/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AsrPageRequestOutputFormat = "text" | "json" | "srt" | "vtt";

export const AsrPageRequestOutputFormat = {
    Text: "text",
    Json: "json",
    Srt: "srt",
    Vtt: "vtt",
} as const;
