/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BotBroadcastFilters {
    /** A list of WhatsApp phone numbers to broadcast to. */
    waPhoneNumberIn?: string[];
    /** A list of Slack user IDs to broadcast to. */
    slackUserIdIn?: string[];
    /** Filter by the Slack user's name. Case insensitive. */
    slackUserNameIcontains?: string;
    /** Filter by whether the Slack channel is personal. By default, will broadcast to both public and personal slack channels. */
    slackChannelIsPersonal?: boolean;
}
