/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface BulkEvalPageOutput {
    outputDocuments: string[];
    finalPrompts?: string[][];
    aggregations?: Gooey.AggFunctionResult[][];
    calledFunctions?: Gooey.CalledFunctionResponse[];
}
