/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CalledFunctionResponseTrigger = "pre" | "post";

export const CalledFunctionResponseTrigger = {
    Pre: "pre",
    Post: "post",
} as const;
