/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface ChyronPlantPageRequest {
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    midiNotes: string;
    midiNotesPrompt?: string;
    chyronPrompt?: string;
    settings?: Gooey.RunSettings;
}
