/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CompareUpscalerPageRequestSelectedModelsItem =
    | "gfpgan_1_4"
    | "real_esrgan_x2"
    | "sd_x4"
    | "real_esrgan"
    | "gfpgan";

export const CompareUpscalerPageRequestSelectedModelsItem = {
    Gfpgan14: "gfpgan_1_4",
    RealEsrganX2: "real_esrgan_x2",
    SdX4: "sd_x4",
    RealEsrgan: "real_esrgan",
    Gfpgan: "gfpgan",
} as const;
