/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export type ConversationEntryContentItem =
    | Gooey.ConversationEntryContentItem.Text
    | Gooey.ConversationEntryContentItem.ImageUrl;

export declare namespace ConversationEntryContentItem {
    interface Text extends Gooey.ChatCompletionContentPartTextParam {
        type: "text";
    }

    interface ImageUrl extends Gooey.ChatCompletionContentPartImageParam {
        type: "image_url";
    }
}
