/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateStreamResponse {
    /** The URL to stream the conversation. Use Server-Sent Events (SSE) to stream the response. */
    streamUrl: string;
}
