/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface DocSummaryPageOutput {
    outputText: string[];
    promptTree?: Gooey.PromptTreeNode[];
    finalPrompt: string;
    calledFunctions?: Gooey.CalledFunctionResponse[];
}
