/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmailFaceInpaintingPageRequestSelectedModel = "sd_2" | "runway_ml" | "dall_e" | "jack_qiao";

export const EmailFaceInpaintingPageRequestSelectedModel = {
    Sd2: "sd_2",
    RunwayMl: "runway_ml",
    DallE: "dall_e",
    JackQiao: "jack_qiao",
} as const;
