/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FailedResponseDetail {
    /** Unique ID for this run */
    id?: string;
    /** Web URL for this run */
    url?: string;
    /** Time when the run was created as ISO format */
    createdAt?: string;
    /** Error message if the run failed */
    error?: string;
}
