/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * When to run this function. `pre` runs before the recipe, `post` runs after the recipe.
 */
export type GoogleGptPageRequestFunctionsItemTrigger = "pre" | "post";

export const GoogleGptPageRequestFunctionsItemTrigger = {
    Pre: "pre",
    Post: "post",
} as const;
