/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ImageSegmentationPageRequestSelectedModel = "dis" | "u2net";

export const ImageSegmentationPageRequestSelectedModel = {
    Dis: "dis",
    U2Net: "u2net",
} as const;
