/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface Img2ImgPageRequest {
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    inputImage: string;
    textPrompt?: string;
    selectedModel?: Gooey.Img2ImgPageRequestSelectedModel;
    selectedControlnetModel?: Gooey.Img2ImgPageRequestSelectedControlnetModel;
    negativePrompt?: string;
    numOutputs?: number;
    quality?: number;
    outputWidth?: number;
    outputHeight?: number;
    guidanceScale?: number;
    promptStrength?: number;
    controlnetConditioningScale?: number[];
    seed?: number;
    imageGuidanceScale?: number;
    settings?: Gooey.RunSettings;
}
