/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LipsyncTtsPageRequestTtsProvider =
    | "GOOGLE_TTS"
    | "ELEVEN_LABS"
    | "UBERDUCK"
    | "BARK"
    | "AZURE_TTS"
    | "OPEN_AI";

export const LipsyncTtsPageRequestTtsProvider = {
    GoogleTts: "GOOGLE_TTS",
    ElevenLabs: "ELEVEN_LABS",
    Uberduck: "UBERDUCK",
    Bark: "BARK",
    AzureTts: "AZURE_TTS",
    OpenAi: "OPEN_AI",
} as const;
