/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LipsyncTtsPageRequestSelectedModel = "Wav2Lip" | "SadTalker";

export const LipsyncTtsPageRequestSelectedModel = {
    Wav2Lip: "Wav2Lip",
    SadTalker: "SadTalker",
} as const;
