/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * When to run this function. `pre` runs before the recipe, `post` runs after the recipe.
 */
export type PortraitRequestFunctionsItemTrigger = "pre" | "post";

export const PortraitRequestFunctionsItemTrigger = {
    Pre: "pre",
    Post: "post",
} as const;
