/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostV3DocSummaryAsyncFormRequestSelectedAsrModel =
    | "whisper_large_v2"
    | "whisper_large_v3"
    | "whisper_hindi_large_v2"
    | "whisper_telugu_large_v2"
    | "nemo_english"
    | "nemo_hindi"
    | "vakyansh_bhojpuri"
    | "gcp_v1"
    | "usm"
    | "deepgram"
    | "azure"
    | "seamless_m4t_v2"
    | "mms_1b_all"
    | "seamless_m4t";

export const PostV3DocSummaryAsyncFormRequestSelectedAsrModel = {
    WhisperLargeV2: "whisper_large_v2",
    WhisperLargeV3: "whisper_large_v3",
    WhisperHindiLargeV2: "whisper_hindi_large_v2",
    WhisperTeluguLargeV2: "whisper_telugu_large_v2",
    NemoEnglish: "nemo_english",
    NemoHindi: "nemo_hindi",
    VakyanshBhojpuri: "vakyansh_bhojpuri",
    GcpV1: "gcp_v1",
    Usm: "usm",
    Deepgram: "deepgram",
    Azure: "azure",
    SeamlessM4TV2: "seamless_m4t_v2",
    Mms1BAll: "mms_1b_all",
    SeamlessM4T: "seamless_m4t",
} as const;
