/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostV3LipsyncAsyncFormRequestSelectedModel = "Wav2Lip" | "SadTalker";

export const PostV3LipsyncAsyncFormRequestSelectedModel = {
    Wav2Lip: "Wav2Lip",
    SadTalker: "SadTalker",
} as const;
