/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostV3VideoBotsAsyncFormRequestTranslationModel = "google" | "ghana_nlp";

export const PostV3VideoBotsAsyncFormRequestTranslationModel = {
    Google: "google",
    GhanaNlp: "ghana_nlp",
} as const;
