/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostV3VideoBotsAsyncFormRequestResponseFormatType = "text" | "json_object";

export const PostV3VideoBotsAsyncFormRequestResponseFormatType = {
    Text: "text",
    JsonObject: "json_object",
} as const;
