/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostV3DocSearchAsyncFormRequestResponseFormatType = "text" | "json_object";

export const PostV3DocSearchAsyncFormRequestResponseFormatType = {
    Text: "text",
    JsonObject: "json_object",
} as const;
