/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostV3LipsyncTtsAsyncFormRequestOpenaiTtsModel = "tts_1" | "tts_1_hd";

export const PostV3LipsyncTtsAsyncFormRequestOpenaiTtsModel = {
    Tts1: "tts_1",
    Tts1Hd: "tts_1_hd",
} as const;
