/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostV3GoogleGptAsyncFormRequestResponseFormatType = "text" | "json_object";

export const PostV3GoogleGptAsyncFormRequestResponseFormatType = {
    Text: "text",
    JsonObject: "json_object",
} as const;
