/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface PromptTreeNode {
    prompt: Gooey.Prompt;
    children: Gooey.PromptTreeNode[];
}
