/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface RunSettings {
    /** Policy for retaining the run data. */
    retentionPolicy?: Gooey.RunSettingsRetentionPolicy;
}
