/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Scheduler =
    | "singlestep_dpm_solver"
    | "multistep_dpm_solver"
    | "dpm_sde"
    | "dpm_discrete"
    | "dpm_discrete_ancestral"
    | "unipc"
    | "lms_discrete"
    | "heun"
    | "euler"
    | "euler_ancestral"
    | "pndm"
    | "ddpm"
    | "ddim"
    | "deis";

export const Scheduler = {
    SinglestepDpmSolver: "singlestep_dpm_solver",
    MultistepDpmSolver: "multistep_dpm_solver",
    DpmSde: "dpm_sde",
    DpmDiscrete: "dpm_discrete",
    DpmDiscreteAncestral: "dpm_discrete_ancestral",
    Unipc: "unipc",
    LmsDiscrete: "lms_discrete",
    Heun: "heun",
    Euler: "euler",
    EulerAncestral: "euler_ancestral",
    Pndm: "pndm",
    Ddpm: "ddpm",
    Ddim: "ddim",
    Deis: "deis",
} as const;
