/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SeoPeopleAlsoAskDocRequestResponseFormatType = "text" | "json_object";

export const SeoPeopleAlsoAskDocRequestResponseFormatType = {
    Text: "text",
    JsonObject: "json_object",
} as const;
