/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface SeoSummaryPageRequest {
    serpSearchLocation?: Gooey.SerpSearchLocation;
    /** DEPRECATED: use `serp_search_location` instead */
    scaleserpLocations?: string[];
    serpSearchType?: Gooey.SerpSearchType;
    /** DEPRECATED: use `serp_search_type` instead */
    scaleserpSearchField?: string;
    searchQuery: string;
    keywords: string;
    title: string;
    companyUrl: string;
    taskInstructions?: string;
    enableHtml?: boolean;
    selectedModel?: Gooey.SeoSummaryPageRequestSelectedModel;
    samplingTemperature?: number;
    maxTokens?: number;
    numOutputs?: number;
    quality?: number;
    avoidRepetition?: boolean;
    maxSearchUrls?: number;
    enableCrosslinks?: boolean;
    seed?: number;
    settings?: Gooey.RunSettings;
}
