/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type SerpSearchType = "search" | "images" | "videos" | "places" | "news";

export const SerpSearchType = {
    Search: "search",
    Images: "images",
    Videos: "videos",
    Places: "places",
    News: "news",
} as const;
