/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface SmartGptPageRequest {
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    inputPrompt: string;
    cotPrompt?: string;
    reflexionPrompt?: string;
    deraPrompt?: string;
    selectedModel?: Gooey.SmartGptPageRequestSelectedModel;
    avoidRepetition?: boolean;
    numOutputs?: number;
    quality?: number;
    maxTokens?: number;
    samplingTemperature?: number;
    responseFormatType?: Gooey.SmartGptPageRequestResponseFormatType;
    settings?: Gooey.RunSettings;
}
