/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface SocialLookupEmailPageRequest {
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    emailAddress: string;
    inputPrompt?: string;
    selectedModel?: Gooey.SocialLookupEmailPageRequestSelectedModel;
    avoidRepetition?: boolean;
    numOutputs?: number;
    quality?: number;
    maxTokens?: number;
    samplingTemperature?: number;
    responseFormatType?: Gooey.SocialLookupEmailPageRequestResponseFormatType;
    settings?: Gooey.RunSettings;
}
