/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface StreamError {
    /** Details about the error */
    detail: string;
    /** An error occurred. The stream has ended. */
    type?: string;
}
