/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface TranslationPageRequest {
    functions?: Gooey.TranslationPageRequestFunctionsItem[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    texts?: string[];
    selectedModel?: Gooey.TranslationPageRequestSelectedModel;
    translationSource?: string;
    translationTarget?: string;
    glossaryDocument?: string;
    settings?: Gooey.RunSettings;
}
