/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Vcard {
    formatName: string;
    email?: string;
    gender?: string;
    birthdayYear?: number;
    birthdayMonth?: number;
    birthdayDay?: number;
    familyName?: string;
    givenName?: string;
    middleNames?: string;
    honorificPrefixes?: string;
    honorificSuffixes?: string;
    impp?: string;
    address?: string;
    calendarUrl?: string;
    commaSeparatedCategories?: string;
    kind?: string;
    language?: string;
    organization?: string;
    photoUrl?: string;
    logoUrl?: string;
    role?: string;
    timezone?: string;
    jobTitle?: string;
    urls?: string[];
    tel?: string;
    note?: string;
}
