/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface VideoBotsPageRequestMessagesItem {
    role: Gooey.VideoBotsPageRequestMessagesItemRole;
    content: Gooey.VideoBotsPageRequestMessagesItemContent;
    displayName?: string;
}
