/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VideoBotsPageRequestMessagesItemRole = "user" | "system" | "assistant";

export const VideoBotsPageRequestMessagesItemRole = {
    User: "user",
    System: "system",
    Assistant: "assistant",
} as const;
