/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../index";

export interface VideoBotsPageOutput {
    finalPrompt?: Gooey.VideoBotsPageOutputFinalPrompt;
    outputText?: string[];
    outputAudio?: string[];
    outputVideo?: string[];
    rawInputText?: string;
    rawTtsText?: string[];
    rawOutputText?: string[];
    references?: Gooey.SearchReference[];
    finalSearchQuery?: string;
    finalKeywordQuery?: Gooey.VideoBotsPageOutputFinalKeywordQuery;
    outputDocuments?: string[];
    replyButtons?: Gooey.ReplyButton[];
    finishReason?: string[];
    calledFunctions?: Gooey.CalledFunctionResponse[];
}
