/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const CompareLlmPageRequestResponseFormatType: core.serialization.Schema<
    serializers.CompareLlmPageRequestResponseFormatType.Raw,
    Gooey.CompareLlmPageRequestResponseFormatType
> = core.serialization.enum_(["text", "json_object"]);

export declare namespace CompareLlmPageRequestResponseFormatType {
    type Raw = "text" | "json_object";
}
