/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         exampleId: "string",
 *         functions: [{
 *                 url: "string",
 *                 trigger: Gooey.RecipeFunctionTrigger.Pre
 *             }],
 *         variables: {
 *             "string": {
 *                 "key": "value"
 *             }
 *         },
 *         inputPrompt: "string",
 *         selectedModels: [Gooey.CompareLlmPageRequestSelectedModelsItem.Gpt4O],
 *         avoidRepetition: true,
 *         numOutputs: 1,
 *         quality: 1.1,
 *         maxTokens: 1,
 *         samplingTemperature: 1.1,
 *         responseFormatType: Gooey.CompareLlmPageRequestResponseFormatType.Text,
 *         settings: {
 *             retentionPolicy: Gooey.RunSettingsRetentionPolicy.Keep
 *         }
 *     }
 */
export interface CompareLlmPageRequest {
    exampleId?: string;
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    inputPrompt?: string;
    selectedModels?: Gooey.CompareLlmPageRequestSelectedModelsItem[];
    avoidRepetition?: boolean;
    numOutputs?: number;
    quality?: number;
    maxTokens?: number;
    samplingTemperature?: number;
    responseFormatType?: Gooey.CompareLlmPageRequestResponseFormatType;
    settings?: Gooey.RunSettings;
}
