/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         exampleId: "string",
 *         functions: [{
 *                 url: "string",
 *                 trigger: Gooey.RecipeFunctionTrigger.Pre
 *             }],
 *         variables: {
 *             "string": {
 *                 "key": "value"
 *             }
 *         },
 *         searchQuery: "string",
 *         keywordQuery: "string",
 *         documents: ["string"],
 *         maxReferences: 1,
 *         maxContextWords: 1,
 *         scrollJump: 1,
 *         docExtractUrl: "string",
 *         embeddingModel: Gooey.DocSearchPageRequestEmbeddingModel.Openai3Large,
 *         denseWeight: 1.1,
 *         taskInstructions: "string",
 *         queryInstructions: "string",
 *         selectedModel: Gooey.DocSearchPageRequestSelectedModel.Gpt4O,
 *         citationStyle: Gooey.DocSearchPageRequestCitationStyle.Number,
 *         avoidRepetition: true,
 *         numOutputs: 1,
 *         quality: 1.1,
 *         maxTokens: 1,
 *         samplingTemperature: 1.1,
 *         responseFormatType: Gooey.DocSearchPageRequestResponseFormatType.Text,
 *         settings: {
 *             retentionPolicy: Gooey.RunSettingsRetentionPolicy.Keep
 *         }
 *     }
 */
export interface DocSearchPageRequest {
    exampleId?: string;
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    searchQuery: string;
    keywordQuery?: Gooey.DocSearchPageRequestKeywordQuery;
    documents?: string[];
    maxReferences?: number;
    maxContextWords?: number;
    scrollJump?: number;
    docExtractUrl?: string;
    embeddingModel?: Gooey.DocSearchPageRequestEmbeddingModel;
    /**
     * Weightage for dense vs sparse embeddings. `0` for sparse, `1` for dense, `0.5` for equal weight.
     * Generally speaking, dense embeddings excel at understanding the context of the query, whereas sparse vectors excel at keyword matches.
     *
     */
    denseWeight?: number;
    taskInstructions?: string;
    queryInstructions?: string;
    selectedModel?: Gooey.DocSearchPageRequestSelectedModel;
    citationStyle?: Gooey.DocSearchPageRequestCitationStyle;
    avoidRepetition?: boolean;
    numOutputs?: number;
    quality?: number;
    maxTokens?: number;
    samplingTemperature?: number;
    responseFormatType?: Gooey.DocSearchPageRequestResponseFormatType;
    settings?: Gooey.RunSettings;
}
