/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         exampleId: "string",
 *         functions: [{
 *                 url: "string",
 *                 trigger: Gooey.RecipeFunctionTrigger.Pre
 *             }],
 *         variables: {
 *             "string": {
 *                 "key": "value"
 *             }
 *         },
 *         texts: ["string"],
 *         selectedModel: Gooey.EmbeddingsPageRequestSelectedModel.Openai3Large,
 *         settings: {
 *             retentionPolicy: Gooey.RunSettingsRetentionPolicy.Keep
 *         }
 *     }
 */
export interface EmbeddingsPageRequest {
    exampleId?: string;
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    texts: string[];
    selectedModel?: Gooey.EmbeddingsPageRequestSelectedModel;
    settings?: Gooey.RunSettings;
}
