/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         searchQuery: "search_query",
 *         textPrompt: "text_prompt"
 *     }
 */
export interface GoogleImageGenPageRequest {
    exampleId?: string;
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    serpSearchLocation?: Gooey.SerpSearchLocation;
    /** DEPRECATED: use `serp_search_location` instead */
    scaleserpLocations?: string[];
    searchQuery: string;
    textPrompt: string;
    selectedModel?: Gooey.GoogleImageGenPageRequestSelectedModel;
    negativePrompt?: string;
    numOutputs?: number;
    quality?: number;
    guidanceScale?: number;
    promptStrength?: number;
    sd2Upscaling?: boolean;
    seed?: number;
    imageGuidanceScale?: number;
    settings?: Gooey.RunSettings;
}
