/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         inputImage: "input_image",
 *         textPrompt: "text_prompt"
 *     }
 */
export interface ObjectInpaintingPageRequest {
    exampleId?: string;
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    inputImage: string;
    textPrompt: string;
    objScale?: number;
    objPosX?: number;
    objPosY?: number;
    maskThreshold?: number;
    selectedModel?: Gooey.ObjectInpaintingPageRequestSelectedModel;
    negativePrompt?: string;
    numOutputs?: number;
    quality?: number;
    outputWidth?: number;
    outputHeight?: number;
    guidanceScale?: number;
    sd2Upscaling?: boolean;
    seed?: number;
    settings?: Gooey.RunSettings;
}
