/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         exampleId: "string",
 *         functions: [{
 *                 url: "string",
 *                 trigger: Gooey.RecipeFunctionTrigger.Pre
 *             }],
 *         variables: {
 *             "string": {
 *                 "key": "value"
 *             }
 *         },
 *         inputImage: "string",
 *         textPrompt: "string",
 *         objScale: 1.1,
 *         objPosX: 1.1,
 *         objPosY: 1.1,
 *         maskThreshold: 1.1,
 *         selectedModel: Gooey.ObjectInpaintingPageRequestSelectedModel.Sd2,
 *         negativePrompt: "string",
 *         numOutputs: 1,
 *         quality: 1,
 *         outputWidth: 1,
 *         outputHeight: 1,
 *         guidanceScale: 1.1,
 *         sd2Upscaling: true,
 *         seed: 1,
 *         settings: {
 *             retentionPolicy: Gooey.RunSettingsRetentionPolicy.Keep
 *         }
 *     }
 */
export interface ObjectInpaintingPageRequest {
    exampleId?: string;
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    inputImage: string;
    textPrompt: string;
    objScale?: number;
    objPosX?: number;
    objPosY?: number;
    maskThreshold?: number;
    selectedModel?: Gooey.ObjectInpaintingPageRequestSelectedModel;
    negativePrompt?: string;
    numOutputs?: number;
    quality?: number;
    outputWidth?: number;
    outputHeight?: number;
    guidanceScale?: number;
    sd2Upscaling?: boolean;
    seed?: number;
    settings?: Gooey.RunSettings;
}
