/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         textPrompt: "text_prompt"
 *     }
 */
export interface PortraitRequest {
    exampleId?: string;
    functions?: Gooey.PortraitRequestFunctionsItem[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    textPrompt: string;
    faceScale?: number;
    facePosX?: number;
    facePosY?: number;
    selectedModel?: Gooey.PortraitRequestSelectedModel;
    negativePrompt?: string;
    numOutputs?: number;
    quality?: number;
    upscaleFactor?: number;
    outputWidth?: number;
    outputHeight?: number;
    guidanceScale?: number;
    seed?: number;
    settings?: Gooey.RunSettings;
}
