/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         documents: ["documents"]
 *     }
 */
export interface PostV3DocSummaryAsyncFormRequest {
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    documents: string[];
    taskInstructions?: string;
    mergeInstructions?: string;
    selectedModel?: Gooey.PostV3DocSummaryAsyncFormRequestSelectedModel;
    chainType?: "map_reduce";
    selectedAsrModel?: Gooey.PostV3DocSummaryAsyncFormRequestSelectedAsrModel;
    googleTranslateTarget?: string;
    avoidRepetition?: boolean;
    numOutputs?: number;
    quality?: number;
    maxTokens?: number;
    samplingTemperature?: number;
    responseFormatType?: Gooey.PostV3DocSummaryAsyncFormRequestResponseFormatType;
    settings?: Gooey.RunSettings;
}
