/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         scale: 1
 *     }
 */
export interface PostV3CompareAiUpscalersAsyncFormRequest {
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    /** Input Image */
    inputImage?: string;
    /** Input Video */
    inputVideo?: string;
    /** The final upsampling scale of the image */
    scale: number;
    selectedModels?: Gooey.PostV3CompareAiUpscalersAsyncFormRequestSelectedModelsItem[];
    selectedBgModel?: "real_esrgan_x2";
    settings?: Gooey.RunSettings;
}
