/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         inputImage: "input_image"
 *     }
 */
export interface PostV3Img2ImgAsyncFormRequest {
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    inputImage: string;
    textPrompt?: string;
    selectedModel?: Gooey.PostV3Img2ImgAsyncFormRequestSelectedModel;
    selectedControlnetModel?: Gooey.PostV3Img2ImgAsyncFormRequestSelectedControlnetModel;
    negativePrompt?: string;
    numOutputs?: number;
    quality?: number;
    outputWidth?: number;
    outputHeight?: number;
    guidanceScale?: number;
    promptStrength?: number;
    controlnetConditioningScale?: number[];
    seed?: number;
    imageGuidanceScale?: number;
    settings?: Gooey.RunSettings;
}
