/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         midiNotes: "midi_notes"
 *     }
 */
export interface PostV3ChyronPlantAsyncFormRequest {
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    midiNotes: string;
    midiNotesPrompt?: string;
    chyronPrompt?: string;
    settings?: Gooey.RunSettings;
}
