/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         emailAddress: "email_address"
 *     }
 */
export interface PostV3SocialLookupEmailAsyncFormRequest {
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    emailAddress: string;
    inputPrompt?: string;
    selectedModel?: Gooey.PostV3SocialLookupEmailAsyncFormRequestSelectedModel;
    avoidRepetition?: boolean;
    numOutputs?: number;
    quality?: number;
    maxTokens?: number;
    samplingTemperature?: number;
    responseFormatType?: Gooey.PostV3SocialLookupEmailAsyncFormRequestResponseFormatType;
    settings?: Gooey.RunSettings;
}
