/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         textPrompt: "text_prompt"
 *     }
 */
export interface QrCodeRequest {
    exampleId?: string;
    functions?: Gooey.QrCodeRequestFunctionsItem[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    qrCodeData?: string;
    qrCodeVcard?: Gooey.QrCodeRequestQrCodeVcard;
    useUrlShortener?: boolean;
    textPrompt: string;
    negativePrompt?: string;
    imagePrompt?: string;
    imagePromptControlnetModels?: Gooey.QrCodeRequestImagePromptControlnetModelsItem[];
    imagePromptStrength?: number;
    imagePromptScale?: number;
    imagePromptPosX?: number;
    imagePromptPosY?: number;
    selectedModel?: Gooey.QrCodeRequestSelectedModel;
    selectedControlnetModel?: Gooey.QrCodeRequestSelectedControlnetModelItem[];
    outputWidth?: number;
    outputHeight?: number;
    guidanceScale?: number;
    controlnetConditioningScale?: number[];
    numOutputs?: number;
    quality?: number;
    scheduler?: Gooey.QrCodeRequestScheduler;
    seed?: number;
    objScale?: number;
    objPosX?: number;
    objPosY?: number;
    settings?: Gooey.RunSettings;
}
