/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         searchQuery: "search_query",
 *         siteFilter: "site_filter"
 *     }
 */
export interface RelatedQnAPageRequest {
    exampleId?: string;
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    searchQuery: string;
    siteFilter: string;
    taskInstructions?: string;
    queryInstructions?: string;
    selectedModel?: Gooey.RelatedQnAPageRequestSelectedModel;
    maxSearchUrls?: number;
    maxReferences?: number;
    maxContextWords?: number;
    scrollJump?: number;
    embeddingModel?: Gooey.RelatedQnAPageRequestEmbeddingModel;
    /**
     * Weightage for dense vs sparse embeddings. `0` for sparse, `1` for dense, `0.5` for equal weight.
     * Generally speaking, dense embeddings excel at understanding the context of the query, whereas sparse vectors excel at keyword matches.
     *
     */
    denseWeight?: number;
    avoidRepetition?: boolean;
    numOutputs?: number;
    quality?: number;
    maxTokens?: number;
    samplingTemperature?: number;
    responseFormatType?: Gooey.RelatedQnAPageRequestResponseFormatType;
    serpSearchLocation?: Gooey.SerpSearchLocation;
    /** DEPRECATED: use `serp_search_location` instead */
    scaleserpLocations?: string[];
    serpSearchType?: Gooey.SerpSearchType;
    /** DEPRECATED: use `serp_search_type` instead */
    scaleserpSearchField?: string;
    settings?: Gooey.RunSettings;
}
