/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {}
 */
export interface RemoveBackgroundRequest {
    exampleId?: string;
    functions?: Gooey.RemoveBackgroundRequestFunctionsItem[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    selectedModel?: Gooey.RemoveBackgroundRequestSelectedModel;
    maskThreshold?: number;
    rectPersepectiveTransform?: boolean;
    reflectionOpacity?: number;
    objScale?: number;
    objPosX?: number;
    objPosY?: number;
    settings?: Gooey.RunSettings;
}
