/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {}
 */
export interface SpeechRecognitionRequest {
    exampleId?: string;
    functions?: Gooey.SpeechRecognitionRequestFunctionsItem[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    selectedModel?: Gooey.SpeechRecognitionRequestSelectedModel;
    language?: string;
    translationModel?: Gooey.SpeechRecognitionRequestTranslationModel;
    outputFormat?: Gooey.SpeechRecognitionRequestOutputFormat;
    /** use `translation_model` & `translation_target` instead. */
    googleTranslateTarget?: string;
    translationSource?: string;
    translationTarget?: string;
    settings?: Gooey.RunSettings;
}
