/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {}
 */
export interface SynthesizeDataRequest {
    exampleId?: string;
    functions?: Gooey.SynthesizeDataRequestFunctionsItem[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    selectedAsrModel?: Gooey.SynthesizeDataRequestSelectedAsrModel;
    googleTranslateTarget?: string;
    taskInstructions?: string;
    selectedModel?: Gooey.SynthesizeDataRequestSelectedModel;
    avoidRepetition?: boolean;
    numOutputs?: number;
    quality?: number;
    maxTokens?: number;
    samplingTemperature?: number;
    responseFormatType?: Gooey.SynthesizeDataRequestResponseFormatType;
    settings?: Gooey.RunSettings;
}
