/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         exampleId: "string",
 *         functions: [{
 *                 url: "string",
 *                 trigger: Gooey.RecipeFunctionTrigger.Pre
 *             }],
 *         variables: {
 *             "string": {
 *                 "key": "value"
 *             }
 *         },
 *         textPrompt: "string",
 *         ttsProvider: Gooey.TextToSpeechPageRequestTtsProvider.GoogleTts,
 *         uberduckVoiceName: "string",
 *         uberduckSpeakingRate: 1.1,
 *         googleVoiceName: "string",
 *         googleSpeakingRate: 1.1,
 *         googlePitch: 1.1,
 *         barkHistoryPrompt: "string",
 *         elevenlabsVoiceName: "string",
 *         elevenlabsApiKey: "string",
 *         elevenlabsVoiceId: "string",
 *         elevenlabsModel: "string",
 *         elevenlabsStability: 1.1,
 *         elevenlabsSimilarityBoost: 1.1,
 *         elevenlabsStyle: 1.1,
 *         elevenlabsSpeakerBoost: true,
 *         azureVoiceName: "string",
 *         openaiVoiceName: Gooey.TextToSpeechPageRequestOpenaiVoiceName.Alloy,
 *         openaiTtsModel: Gooey.TextToSpeechPageRequestOpenaiTtsModel.Tts1,
 *         settings: {
 *             retentionPolicy: Gooey.RunSettingsRetentionPolicy.Keep
 *         }
 *     }
 */
export interface TextToSpeechPageRequest {
    exampleId?: string;
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    textPrompt: string;
    ttsProvider?: Gooey.TextToSpeechPageRequestTtsProvider;
    uberduckVoiceName?: string;
    uberduckSpeakingRate?: number;
    googleVoiceName?: string;
    googleSpeakingRate?: number;
    googlePitch?: number;
    barkHistoryPrompt?: string;
    /** Use `elevenlabs_voice_id` instead */
    elevenlabsVoiceName?: string;
    elevenlabsApiKey?: string;
    elevenlabsVoiceId?: string;
    elevenlabsModel?: string;
    elevenlabsStability?: number;
    elevenlabsSimilarityBoost?: number;
    elevenlabsStyle?: number;
    elevenlabsSpeakerBoost?: boolean;
    azureVoiceName?: string;
    openaiVoiceName?: Gooey.TextToSpeechPageRequestOpenaiVoiceName;
    openaiTtsModel?: Gooey.TextToSpeechPageRequestOpenaiTtsModel;
    settings?: Gooey.RunSettings;
}
