/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../index";

/**
 * @example
 *     {
 *         scale: 1
 *     }
 */
export interface UpscaleRequest {
    exampleId?: string;
    functions?: Gooey.UpscaleRequestFunctionsItem[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    /** The final upsampling scale of the image */
    scale: number;
    selectedModels?: Gooey.UpscaleRequestSelectedModelsItem[];
    selectedBgModel?: "real_esrgan_x2";
    settings?: Gooey.RunSettings;
}
