/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const LipsyncPageRequestSelectedModel: core.serialization.Schema<
    serializers.LipsyncPageRequestSelectedModel.Raw,
    Gooey.LipsyncPageRequestSelectedModel
> = core.serialization.enum_(["Wav2Lip", "SadTalker"]);

export declare namespace LipsyncPageRequestSelectedModel {
    type Raw = "Wav2Lip" | "SadTalker";
}
