/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { AggFunctionResultFunction } from "./AggFunctionResultFunction";

export const AggFunctionResult: core.serialization.ObjectSchema<
    serializers.AggFunctionResult.Raw,
    Gooey.AggFunctionResult
> = core.serialization.object({
    column: core.serialization.string(),
    function: AggFunctionResultFunction,
    count: core.serialization.number(),
    value: core.serialization.number(),
});

export declare namespace AggFunctionResult {
    interface Raw {
        column: string;
        function: AggFunctionResultFunction.Raw;
        count: number;
        value: number;
    }
}
