/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const AnimationPrompt: core.serialization.ObjectSchema<serializers.AnimationPrompt.Raw, Gooey.AnimationPrompt> =
    core.serialization.object({
        frame: core.serialization.string(),
        prompt: core.serialization.string(),
    });

export declare namespace AnimationPrompt {
    interface Raw {
        frame: string;
        prompt: string;
    }
}
