/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { AsrChunk } from "./AsrChunk";

export const AsrOutputJson: core.serialization.ObjectSchema<serializers.AsrOutputJson.Raw, Gooey.AsrOutputJson> =
    core.serialization.object({
        text: core.serialization.string(),
        chunks: core.serialization.list(AsrChunk).optional(),
    });

export declare namespace AsrOutputJson {
    interface Raw {
        text: string;
        chunks?: AsrChunk.Raw[] | null;
    }
}
