/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { AsrPageRequestFunctionsItemTrigger } from "./AsrPageRequestFunctionsItemTrigger";

export const AsrPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.AsrPageRequestFunctionsItem.Raw,
    Gooey.AsrPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: AsrPageRequestFunctionsItemTrigger,
});

export declare namespace AsrPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: AsrPageRequestFunctionsItemTrigger.Raw;
    }
}
