/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormEmbeddings: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormEmbeddings.Raw,
    Gooey.BodyAsyncFormEmbeddings
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormEmbeddings {
    interface Raw {
        json: string;
    }
}
