/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { BulkEvalPageRequest } from "./BulkEvalPageRequest";

export const BodyAsyncFormBulkEval: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormBulkEval.Raw,
    Gooey.BodyAsyncFormBulkEval
> = core.serialization.object({
    pageRequestJson: core.serialization.property("page_request_json", BulkEvalPageRequest),
});

export declare namespace BodyAsyncFormBulkEval {
    interface Raw {
        page_request_json: BulkEvalPageRequest.Raw;
    }
}
