/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormSocialLookupEmail: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormSocialLookupEmail.Raw,
    Gooey.BodyAsyncFormSocialLookupEmail
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormSocialLookupEmail {
    interface Raw {
        json: string;
    }
}
