/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormRelatedQnaMaker: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormRelatedQnaMaker.Raw,
    Gooey.BodyAsyncFormRelatedQnaMaker
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormRelatedQnaMaker {
    interface Raw {
        json: string;
    }
}
