/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { Text2AudioPageRequest } from "./Text2AudioPageRequest";

export const BodyAsyncFormText2Audio: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormText2Audio.Raw,
    Gooey.BodyAsyncFormText2Audio
> = core.serialization.object({
    pageRequestJson: core.serialization.property("page_request_json", Text2AudioPageRequest),
});

export declare namespace BodyAsyncFormText2Audio {
    interface Raw {
        page_request_json: Text2AudioPageRequest.Raw;
    }
}
