/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormCompareAiUpscalers: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormCompareAiUpscalers.Raw,
    Gooey.BodyAsyncFormCompareAiUpscalers
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormCompareAiUpscalers {
    interface Raw {
        json: string;
    }
}
