/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormVideoBots: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormVideoBots.Raw,
    Gooey.BodyAsyncFormVideoBots
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormVideoBots {
    interface Raw {
        json: string;
    }
}
