/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { DocExtractPageRequest } from "./DocExtractPageRequest";

export const BodyAsyncFormDocExtract: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormDocExtract.Raw,
    Gooey.BodyAsyncFormDocExtract
> = core.serialization.object({
    pageRequestJson: core.serialization.property("page_request_json", DocExtractPageRequest),
});

export declare namespace BodyAsyncFormDocExtract {
    interface Raw {
        page_request_json: DocExtractPageRequest.Raw;
    }
}
