/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { SmartGptPageRequest } from "./SmartGptPageRequest";

export const BodyAsyncFormSmartGpt: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormSmartGpt.Raw,
    Gooey.BodyAsyncFormSmartGpt
> = core.serialization.object({
    pageRequestJson: core.serialization.property("page_request_json", SmartGptPageRequest),
});

export declare namespace BodyAsyncFormSmartGpt {
    interface Raw {
        page_request_json: SmartGptPageRequest.Raw;
    }
}
