/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormBulkRunner: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormBulkRunner.Raw,
    Gooey.BodyAsyncFormBulkRunner
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormBulkRunner {
    interface Raw {
        json: string;
    }
}
