/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormImg2Img: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormImg2Img.Raw,
    Gooey.BodyAsyncFormImg2Img
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormImg2Img {
    interface Raw {
        json: string;
    }
}
