/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormDocExtract: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormDocExtract.Raw,
    Gooey.BodyAsyncFormDocExtract
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormDocExtract {
    interface Raw {
        json: string;
    }
}
