/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormFaceInpainting: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormFaceInpainting.Raw,
    Gooey.BodyAsyncFormFaceInpainting
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormFaceInpainting {
    interface Raw {
        json: string;
    }
}
