/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormText2Audio: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormText2Audio.Raw,
    Gooey.BodyAsyncFormText2Audio
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormText2Audio {
    interface Raw {
        json: string;
    }
}
