/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { ObjectInpaintingPageRequest } from "./ObjectInpaintingPageRequest";

export const BodyAsyncFormObjectInpainting: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormObjectInpainting.Raw,
    Gooey.BodyAsyncFormObjectInpainting
> = core.serialization.object({
    pageRequestJson: core.serialization.property("page_request_json", ObjectInpaintingPageRequest),
});

export declare namespace BodyAsyncFormObjectInpainting {
    interface Raw {
        page_request_json: ObjectInpaintingPageRequest.Raw;
    }
}
