/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { LetterWriterPageRequest } from "./LetterWriterPageRequest";

export const BodyAsyncFormLetterWriter: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormLetterWriter.Raw,
    Gooey.BodyAsyncFormLetterWriter
> = core.serialization.object({
    pageRequestJson: core.serialization.property("page_request_json", LetterWriterPageRequest),
});

export declare namespace BodyAsyncFormLetterWriter {
    interface Raw {
        page_request_json: LetterWriterPageRequest.Raw;
    }
}
