/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormAsr: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormAsr.Raw,
    Gooey.BodyAsyncFormAsr
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormAsr {
    interface Raw {
        json: string;
    }
}
