/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { DeforumSdPageRequest } from "./DeforumSdPageRequest";

export const BodyAsyncFormDeforumSd: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormDeforumSd.Raw,
    Gooey.BodyAsyncFormDeforumSd
> = core.serialization.object({
    pageRequestJson: core.serialization.property("page_request_json", DeforumSdPageRequest),
});

export declare namespace BodyAsyncFormDeforumSd {
    interface Raw {
        page_request_json: DeforumSdPageRequest.Raw;
    }
}
