/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { SocialLookupEmailPageRequest } from "./SocialLookupEmailPageRequest";

export const BodyAsyncFormSocialLookupEmail: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormSocialLookupEmail.Raw,
    Gooey.BodyAsyncFormSocialLookupEmail
> = core.serialization.object({
    pageRequestJson: core.serialization.property("page_request_json", SocialLookupEmailPageRequest),
});

export declare namespace BodyAsyncFormSocialLookupEmail {
    interface Raw {
        page_request_json: SocialLookupEmailPageRequest.Raw;
    }
}
