/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormChyronPlant: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormChyronPlant.Raw,
    Gooey.BodyAsyncFormChyronPlant
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormChyronPlant {
    interface Raw {
        json: string;
    }
}
