/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { LipsyncTtsPageRequest } from "./LipsyncTtsPageRequest";

export const BodyAsyncFormLipsyncTts: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormLipsyncTts.Raw,
    Gooey.BodyAsyncFormLipsyncTts
> = core.serialization.object({
    pageRequestJson: core.serialization.property("page_request_json", LipsyncTtsPageRequest),
});

export declare namespace BodyAsyncFormLipsyncTts {
    interface Raw {
        page_request_json: LipsyncTtsPageRequest.Raw;
    }
}
