/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BodyAsyncFormObjectInpainting: core.serialization.ObjectSchema<
    serializers.BodyAsyncFormObjectInpainting.Raw,
    Gooey.BodyAsyncFormObjectInpainting
> = core.serialization.object({
    json: core.serialization.string(),
});

export declare namespace BodyAsyncFormObjectInpainting {
    interface Raw {
        json: string;
    }
}
