/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { BulkRunRequestFunctionsItemTrigger } from "./BulkRunRequestFunctionsItemTrigger";

export const BulkRunRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.BulkRunRequestFunctionsItem.Raw,
    Gooey.BulkRunRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: BulkRunRequestFunctionsItemTrigger,
});

export declare namespace BulkRunRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: BulkRunRequestFunctionsItemTrigger.Raw;
    }
}
