/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { RecipeFunction } from "./RecipeFunction";
import { RunSettings } from "./RunSettings";

export const BulkRunnerPageRequest: core.serialization.ObjectSchema<
    serializers.BulkRunnerPageRequest.Raw,
    Gooey.BulkRunnerPageRequest
> = core.serialization.object({
    functions: core.serialization.list(RecipeFunction).optional(),
    variables: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    documents: core.serialization.list(core.serialization.string()),
    runUrls: core.serialization.property("run_urls", core.serialization.list(core.serialization.string())),
    inputColumns: core.serialization.property(
        "input_columns",
        core.serialization.record(core.serialization.string(), core.serialization.string())
    ),
    outputColumns: core.serialization.property(
        "output_columns",
        core.serialization.record(core.serialization.string(), core.serialization.string())
    ),
    evalUrls: core.serialization.property("eval_urls", core.serialization.list(core.serialization.string()).optional()),
    settings: RunSettings.optional(),
});

export declare namespace BulkRunnerPageRequest {
    interface Raw {
        functions?: RecipeFunction.Raw[] | null;
        variables?: Record<string, unknown> | null;
        documents: string[];
        run_urls: string[];
        input_columns: Record<string, string>;
        output_columns: Record<string, string>;
        eval_urls?: string[] | null;
        settings?: RunSettings.Raw | null;
    }
}
