/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const BulkEvalPageRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.BulkEvalPageRequestFunctionsItemTrigger.Raw,
    Gooey.BulkEvalPageRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace BulkEvalPageRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
