/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { BulkEvalPageRequestAggFunctionsItemFunction } from "./BulkEvalPageRequestAggFunctionsItemFunction";

export const BulkEvalPageRequestAggFunctionsItem: core.serialization.ObjectSchema<
    serializers.BulkEvalPageRequestAggFunctionsItem.Raw,
    Gooey.BulkEvalPageRequestAggFunctionsItem
> = core.serialization.object({
    column: core.serialization.string().optional(),
    function: BulkEvalPageRequestAggFunctionsItemFunction,
});

export declare namespace BulkEvalPageRequestAggFunctionsItem {
    interface Raw {
        column?: string | null;
        function: BulkEvalPageRequestAggFunctionsItemFunction.Raw;
    }
}
