/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const ButtonPressed: core.serialization.ObjectSchema<serializers.ButtonPressed.Raw, Gooey.ButtonPressed> =
    core.serialization.object({
        buttonId: core.serialization.property("button_id", core.serialization.string()),
        contextMsgId: core.serialization.property("context_msg_id", core.serialization.string()),
    });

export declare namespace ButtonPressed {
    interface Raw {
        button_id: string;
        context_msg_id: string;
    }
}
