/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const CompareUpscalerPageRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.CompareUpscalerPageRequestFunctionsItemTrigger.Raw,
    Gooey.CompareUpscalerPageRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace CompareUpscalerPageRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
