/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const CompareText2ImgPageRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.CompareText2ImgPageRequestFunctionsItemTrigger.Raw,
    Gooey.CompareText2ImgPageRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace CompareText2ImgPageRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
