/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { CompareUpscalerPageRequestFunctionsItemTrigger } from "./CompareUpscalerPageRequestFunctionsItemTrigger";

export const CompareUpscalerPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.CompareUpscalerPageRequestFunctionsItem.Raw,
    Gooey.CompareUpscalerPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: CompareUpscalerPageRequestFunctionsItemTrigger,
});

export declare namespace CompareUpscalerPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: CompareUpscalerPageRequestFunctionsItemTrigger.Raw;
    }
}
