/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { CompareText2ImgPageRequestFunctionsItemTrigger } from "./CompareText2ImgPageRequestFunctionsItemTrigger";

export const CompareText2ImgPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.CompareText2ImgPageRequestFunctionsItem.Raw,
    Gooey.CompareText2ImgPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: CompareText2ImgPageRequestFunctionsItemTrigger,
});

export declare namespace CompareText2ImgPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: CompareText2ImgPageRequestFunctionsItemTrigger.Raw;
    }
}
