/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { CompareLlmPageRequestFunctionsItemTrigger } from "./CompareLlmPageRequestFunctionsItemTrigger";

export const CompareLlmPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.CompareLlmPageRequestFunctionsItem.Raw,
    Gooey.CompareLlmPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: CompareLlmPageRequestFunctionsItemTrigger,
});

export declare namespace CompareLlmPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: CompareLlmPageRequestFunctionsItemTrigger.Raw;
    }
}
