/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { CompareText2ImgPageOutput } from "./CompareText2ImgPageOutput";

export const CompareText2ImgPageResponse: core.serialization.ObjectSchema<
    serializers.CompareText2ImgPageResponse.Raw,
    Gooey.CompareText2ImgPageResponse
> = core.serialization.object({
    id: core.serialization.string(),
    url: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    output: CompareText2ImgPageOutput,
});

export declare namespace CompareText2ImgPageResponse {
    interface Raw {
        id: string;
        url: string;
        created_at: string;
        output: CompareText2ImgPageOutput.Raw;
    }
}
