/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const ConversationEntryRole: core.serialization.Schema<
    serializers.ConversationEntryRole.Raw,
    Gooey.ConversationEntryRole
> = core.serialization.enum_(["user", "system", "assistant"]);

export declare namespace ConversationEntryRole {
    type Raw = "user" | "system" | "assistant";
}
