/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const CreateStreamResponse: core.serialization.ObjectSchema<
    serializers.CreateStreamResponse.Raw,
    Gooey.CreateStreamResponse
> = core.serialization.object({
    streamUrl: core.serialization.property("stream_url", core.serialization.string()),
});

export declare namespace CreateStreamResponse {
    interface Raw {
        stream_url: string;
    }
}
