/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const DeforumSdPageRequestSelectedModel: core.serialization.Schema<
    serializers.DeforumSdPageRequestSelectedModel.Raw,
    Gooey.DeforumSdPageRequestSelectedModel
> = core.serialization.enum_(["protogen_2_2", "epicdream"]);

export declare namespace DeforumSdPageRequestSelectedModel {
    type Raw = "protogen_2_2" | "epicdream";
}
