/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const DeforumSdPageRequestAnimationPromptsItem: core.serialization.ObjectSchema<
    serializers.DeforumSdPageRequestAnimationPromptsItem.Raw,
    Gooey.DeforumSdPageRequestAnimationPromptsItem
> = core.serialization.object({
    frame: core.serialization.string(),
    prompt: core.serialization.string(),
});

export declare namespace DeforumSdPageRequestAnimationPromptsItem {
    interface Raw {
        frame: string;
        prompt: string;
    }
}
