/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const DeforumSdPageRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.DeforumSdPageRequestFunctionsItemTrigger.Raw,
    Gooey.DeforumSdPageRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace DeforumSdPageRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
