/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const Detail: core.serialization.Schema<serializers.Detail.Raw, Gooey.Detail> = core.serialization.enum_([
    "auto",
    "low",
    "high",
]);

export declare namespace Detail {
    type Raw = "auto" | "low" | "high";
}
