/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { DocExtractPageRequestFunctionsItemTrigger } from "./DocExtractPageRequestFunctionsItemTrigger";

export const DocExtractPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.DocExtractPageRequestFunctionsItem.Raw,
    Gooey.DocExtractPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: DocExtractPageRequestFunctionsItemTrigger,
});

export declare namespace DocExtractPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: DocExtractPageRequestFunctionsItemTrigger.Raw;
    }
}
