/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { RecipeFunction } from "./RecipeFunction";
import { DocExtractPageRequestSelectedAsrModel } from "./DocExtractPageRequestSelectedAsrModel";
import { DocExtractPageRequestSelectedModel } from "./DocExtractPageRequestSelectedModel";
import { RunSettings } from "./RunSettings";

export const DocExtractPageRequest: core.serialization.ObjectSchema<
    serializers.DocExtractPageRequest.Raw,
    Gooey.DocExtractPageRequest
> = core.serialization.object({
    functions: core.serialization.list(RecipeFunction).optional(),
    variables: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    documents: core.serialization.list(core.serialization.string()),
    sheetUrl: core.serialization.property("sheet_url", core.serialization.string().optional()),
    selectedAsrModel: core.serialization.property(
        "selected_asr_model",
        DocExtractPageRequestSelectedAsrModel.optional()
    ),
    googleTranslateTarget: core.serialization.property(
        "google_translate_target",
        core.serialization.string().optional()
    ),
    glossaryDocument: core.serialization.property("glossary_document", core.serialization.string().optional()),
    taskInstructions: core.serialization.property("task_instructions", core.serialization.string().optional()),
    selectedModel: core.serialization.property("selected_model", DocExtractPageRequestSelectedModel.optional()),
    avoidRepetition: core.serialization.property("avoid_repetition", core.serialization.boolean().optional()),
    numOutputs: core.serialization.property("num_outputs", core.serialization.number().optional()),
    quality: core.serialization.number().optional(),
    maxTokens: core.serialization.property("max_tokens", core.serialization.number().optional()),
    samplingTemperature: core.serialization.property("sampling_temperature", core.serialization.number().optional()),
    settings: RunSettings.optional(),
});

export declare namespace DocExtractPageRequest {
    interface Raw {
        functions?: RecipeFunction.Raw[] | null;
        variables?: Record<string, unknown> | null;
        documents: string[];
        sheet_url?: string | null;
        selected_asr_model?: DocExtractPageRequestSelectedAsrModel.Raw | null;
        google_translate_target?: string | null;
        glossary_document?: string | null;
        task_instructions?: string | null;
        selected_model?: DocExtractPageRequestSelectedModel.Raw | null;
        avoid_repetition?: boolean | null;
        num_outputs?: number | null;
        quality?: number | null;
        max_tokens?: number | null;
        sampling_temperature?: number | null;
        settings?: RunSettings.Raw | null;
    }
}
