/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { RecipeFunction } from "./RecipeFunction";
import { DocSummaryPageRequestSelectedModel } from "./DocSummaryPageRequestSelectedModel";
import { DocSummaryPageRequestSelectedAsrModel } from "./DocSummaryPageRequestSelectedAsrModel";
import { RunSettings } from "./RunSettings";

export const DocSummaryPageRequest: core.serialization.ObjectSchema<
    serializers.DocSummaryPageRequest.Raw,
    Gooey.DocSummaryPageRequest
> = core.serialization.object({
    functions: core.serialization.list(RecipeFunction).optional(),
    variables: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    documents: core.serialization.list(core.serialization.string()),
    taskInstructions: core.serialization.property("task_instructions", core.serialization.string().optional()),
    mergeInstructions: core.serialization.property("merge_instructions", core.serialization.string().optional()),
    selectedModel: core.serialization.property("selected_model", DocSummaryPageRequestSelectedModel.optional()),
    avoidRepetition: core.serialization.property("avoid_repetition", core.serialization.boolean().optional()),
    numOutputs: core.serialization.property("num_outputs", core.serialization.number().optional()),
    quality: core.serialization.number().optional(),
    maxTokens: core.serialization.property("max_tokens", core.serialization.number().optional()),
    samplingTemperature: core.serialization.property("sampling_temperature", core.serialization.number().optional()),
    chainType: core.serialization.property("chain_type", core.serialization.stringLiteral("map_reduce").optional()),
    selectedAsrModel: core.serialization.property(
        "selected_asr_model",
        DocSummaryPageRequestSelectedAsrModel.optional()
    ),
    googleTranslateTarget: core.serialization.property(
        "google_translate_target",
        core.serialization.string().optional()
    ),
    settings: RunSettings.optional(),
});

export declare namespace DocSummaryPageRequest {
    interface Raw {
        functions?: RecipeFunction.Raw[] | null;
        variables?: Record<string, unknown> | null;
        documents: string[];
        task_instructions?: string | null;
        merge_instructions?: string | null;
        selected_model?: DocSummaryPageRequestSelectedModel.Raw | null;
        avoid_repetition?: boolean | null;
        num_outputs?: number | null;
        quality?: number | null;
        max_tokens?: number | null;
        sampling_temperature?: number | null;
        chain_type?: "map_reduce" | null;
        selected_asr_model?: DocSummaryPageRequestSelectedAsrModel.Raw | null;
        google_translate_target?: string | null;
        settings?: RunSettings.Raw | null;
    }
}
