/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const DocSearchPageRequestKeywordQuery: core.serialization.Schema<
    serializers.DocSearchPageRequestKeywordQuery.Raw,
    Gooey.DocSearchPageRequestKeywordQuery
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace DocSearchPageRequestKeywordQuery {
    type Raw = string | string[];
}
