/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { DocSummaryRequestFunctionsItemTrigger } from "./DocSummaryRequestFunctionsItemTrigger";

export const DocSummaryRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.DocSummaryRequestFunctionsItem.Raw,
    Gooey.DocSummaryRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: DocSummaryRequestFunctionsItemTrigger,
});

export declare namespace DocSummaryRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: DocSummaryRequestFunctionsItemTrigger.Raw;
    }
}
