/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { SearchReference } from "./SearchReference";
import { CalledFunctionResponse } from "./CalledFunctionResponse";

export const DocSearchPageOutput: core.serialization.ObjectSchema<
    serializers.DocSearchPageOutput.Raw,
    Gooey.DocSearchPageOutput
> = core.serialization.object({
    outputText: core.serialization.property("output_text", core.serialization.list(core.serialization.string())),
    references: core.serialization.list(SearchReference),
    finalPrompt: core.serialization.property("final_prompt", core.serialization.string()),
    finalSearchQuery: core.serialization.property("final_search_query", core.serialization.string().optional()),
    calledFunctions: core.serialization.property(
        "called_functions",
        core.serialization.list(CalledFunctionResponse).optional()
    ),
});

export declare namespace DocSearchPageOutput {
    interface Raw {
        output_text: string[];
        references: SearchReference.Raw[];
        final_prompt: string;
        final_search_query?: string | null;
        called_functions?: CalledFunctionResponse.Raw[] | null;
    }
}
