/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const DocSummaryPageRequestResponseFormatType: core.serialization.Schema<
    serializers.DocSummaryPageRequestResponseFormatType.Raw,
    Gooey.DocSummaryPageRequestResponseFormatType
> = core.serialization.enum_(["text", "json_object"]);

export declare namespace DocSummaryPageRequestResponseFormatType {
    type Raw = "text" | "json_object";
}
