/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const DocSummaryRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.DocSummaryRequestFunctionsItemTrigger.Raw,
    Gooey.DocSummaryRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace DocSummaryRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
