/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { DocSearchPageOutput } from "./DocSearchPageOutput";

export const DocSearchPageResponse: core.serialization.ObjectSchema<
    serializers.DocSearchPageResponse.Raw,
    Gooey.DocSearchPageResponse
> = core.serialization.object({
    id: core.serialization.string(),
    url: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    output: DocSearchPageOutput,
});

export declare namespace DocSearchPageResponse {
    interface Raw {
        id: string;
        url: string;
        created_at: string;
        output: DocSearchPageOutput.Raw;
    }
}
