/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { CalledFunctionResponse } from "./CalledFunctionResponse";

export const EmbeddingsPageOutput: core.serialization.ObjectSchema<
    serializers.EmbeddingsPageOutput.Raw,
    Gooey.EmbeddingsPageOutput
> = core.serialization.object({
    embeddings: core.serialization.list(core.serialization.list(core.serialization.number())),
    calledFunctions: core.serialization.property(
        "called_functions",
        core.serialization.list(CalledFunctionResponse).optional()
    ),
});

export declare namespace EmbeddingsPageOutput {
    interface Raw {
        embeddings: number[][];
        called_functions?: CalledFunctionResponse.Raw[] | null;
    }
}
