/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { FaceInpaintingPageRequestFunctionsItemTrigger } from "./FaceInpaintingPageRequestFunctionsItemTrigger";

export const FaceInpaintingPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.FaceInpaintingPageRequestFunctionsItem.Raw,
    Gooey.FaceInpaintingPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: FaceInpaintingPageRequestFunctionsItemTrigger,
});

export declare namespace FaceInpaintingPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: FaceInpaintingPageRequestFunctionsItemTrigger.Raw;
    }
}
