/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const FaceInpaintingPageRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.FaceInpaintingPageRequestFunctionsItemTrigger.Raw,
    Gooey.FaceInpaintingPageRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace FaceInpaintingPageRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
