/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { FailedResponseDetail } from "./FailedResponseDetail";

export const FailedReponseModelV2: core.serialization.ObjectSchema<
    serializers.FailedReponseModelV2.Raw,
    Gooey.FailedReponseModelV2
> = core.serialization.object({
    detail: FailedResponseDetail,
});

export declare namespace FailedReponseModelV2 {
    interface Raw {
        detail: FailedResponseDetail.Raw;
    }
}
