/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { FunctionsPageOutput } from "./FunctionsPageOutput";

export const FunctionsPageResponse: core.serialization.ObjectSchema<
    serializers.FunctionsPageResponse.Raw,
    Gooey.FunctionsPageResponse
> = core.serialization.object({
    id: core.serialization.string(),
    url: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    output: FunctionsPageOutput,
});

export declare namespace FunctionsPageResponse {
    interface Raw {
        id: string;
        url: string;
        created_at: string;
        output: FunctionsPageOutput.Raw;
    }
}
