/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const GoogleGptPageRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.GoogleGptPageRequestFunctionsItemTrigger.Raw,
    Gooey.GoogleGptPageRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace GoogleGptPageRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
