/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { GoogleGptPageOutput } from "./GoogleGptPageOutput";

export const GoogleGptPageResponse: core.serialization.ObjectSchema<
    serializers.GoogleGptPageResponse.Raw,
    Gooey.GoogleGptPageResponse
> = core.serialization.object({
    id: core.serialization.string(),
    url: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    output: GoogleGptPageOutput,
});

export declare namespace GoogleGptPageResponse {
    interface Raw {
        id: string;
        url: string;
        created_at: string;
        output: GoogleGptPageOutput.Raw;
    }
}
