/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const ImageSegmentationPageRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.ImageSegmentationPageRequestFunctionsItemTrigger.Raw,
    Gooey.ImageSegmentationPageRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace ImageSegmentationPageRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
