/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const ImageSegmentationPageRequestSelectedModel: core.serialization.Schema<
    serializers.ImageSegmentationPageRequestSelectedModel.Raw,
    Gooey.ImageSegmentationPageRequestSelectedModel
> = core.serialization.enum_(["dis", "u2net"]);

export declare namespace ImageSegmentationPageRequestSelectedModel {
    type Raw = "dis" | "u2net";
}
