/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { Img2ImgPageRequestFunctionsItemTrigger } from "./Img2ImgPageRequestFunctionsItemTrigger";

export const Img2ImgPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.Img2ImgPageRequestFunctionsItem.Raw,
    Gooey.Img2ImgPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: Img2ImgPageRequestFunctionsItemTrigger,
});

export declare namespace Img2ImgPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: Img2ImgPageRequestFunctionsItemTrigger.Raw;
    }
}
