/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const Img2ImgPageRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.Img2ImgPageRequestFunctionsItemTrigger.Raw,
    Gooey.Img2ImgPageRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace Img2ImgPageRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
