/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { CalledFunctionResponse } from "./CalledFunctionResponse";

export const Img2ImgPageOutput: core.serialization.ObjectSchema<
    serializers.Img2ImgPageOutput.Raw,
    Gooey.Img2ImgPageOutput
> = core.serialization.object({
    outputImages: core.serialization.property("output_images", core.serialization.list(core.serialization.string())),
    calledFunctions: core.serialization.property(
        "called_functions",
        core.serialization.list(CalledFunctionResponse).optional()
    ),
});

export declare namespace Img2ImgPageOutput {
    interface Raw {
        output_images: string[];
        called_functions?: CalledFunctionResponse.Raw[] | null;
    }
}
