/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { CalledFunctionResponse } from "./CalledFunctionResponse";

export const LetterWriterPageOutput: core.serialization.ObjectSchema<
    serializers.LetterWriterPageOutput.Raw,
    Gooey.LetterWriterPageOutput
> = core.serialization.object({
    outputLetters: core.serialization.property("output_letters", core.serialization.list(core.serialization.string())),
    responseJson: core.serialization.property("response_json", core.serialization.unknown().optional()),
    generatedInputPrompt: core.serialization.property("generated_input_prompt", core.serialization.string()),
    finalPrompt: core.serialization.property("final_prompt", core.serialization.string()),
    calledFunctions: core.serialization.property(
        "called_functions",
        core.serialization.list(CalledFunctionResponse).optional()
    ),
});

export declare namespace LetterWriterPageOutput {
    interface Raw {
        output_letters: string[];
        response_json?: unknown | null;
        generated_input_prompt: string;
        final_prompt: string;
        called_functions?: CalledFunctionResponse.Raw[] | null;
    }
}
