/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const LetterWriterPageRequestExampleLettersItem: core.serialization.ObjectSchema<
    serializers.LetterWriterPageRequestExampleLettersItem.Raw,
    Gooey.LetterWriterPageRequestExampleLettersItem
> = core.serialization.object({
    prompt: core.serialization.string(),
    completion: core.serialization.string(),
});

export declare namespace LetterWriterPageRequestExampleLettersItem {
    interface Raw {
        prompt: string;
        completion: string;
    }
}
