/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const Level: core.serialization.Schema<serializers.Level.Raw, Gooey.Level> = core.serialization.enum_([
    "log",
    "error",
]);

export declare namespace Level {
    type Raw = "log" | "error";
}
