/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { LipsyncPageRequestFunctionsItemTrigger } from "./LipsyncPageRequestFunctionsItemTrigger";

export const LipsyncPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.LipsyncPageRequestFunctionsItem.Raw,
    Gooey.LipsyncPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: LipsyncPageRequestFunctionsItemTrigger,
});

export declare namespace LipsyncPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: LipsyncPageRequestFunctionsItemTrigger.Raw;
    }
}
