/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { LipsyncPageOutput } from "./LipsyncPageOutput";

export const LipsyncPageResponse: core.serialization.ObjectSchema<
    serializers.LipsyncPageResponse.Raw,
    Gooey.LipsyncPageResponse
> = core.serialization.object({
    id: core.serialization.string(),
    url: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    output: LipsyncPageOutput,
});

export declare namespace LipsyncPageResponse {
    interface Raw {
        id: string;
        url: string;
        created_at: string;
        output: LipsyncPageOutput.Raw;
    }
}
