/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { LipsyncTtsPageRequestFunctionsItemTrigger } from "./LipsyncTtsPageRequestFunctionsItemTrigger";

export const LipsyncTtsPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.LipsyncTtsPageRequestFunctionsItem.Raw,
    Gooey.LipsyncTtsPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: LipsyncTtsPageRequestFunctionsItemTrigger,
});

export declare namespace LipsyncTtsPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: LipsyncTtsPageRequestFunctionsItemTrigger.Raw;
    }
}
