/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const LipsyncRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.LipsyncRequestFunctionsItemTrigger.Raw,
    Gooey.LipsyncRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace LipsyncRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
