/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const LipsyncTtsRequestSadtalkerSettingsPreprocess: core.serialization.Schema<
    serializers.LipsyncTtsRequestSadtalkerSettingsPreprocess.Raw,
    Gooey.LipsyncTtsRequestSadtalkerSettingsPreprocess
> = core.serialization.enum_(["crop", "extcrop", "resize", "full", "extfull"]);

export declare namespace LipsyncTtsRequestSadtalkerSettingsPreprocess {
    type Raw = "crop" | "extcrop" | "resize" | "full" | "extfull";
}
