/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { RecipeFunction } from "./RecipeFunction";
import { SadTalkerSettings } from "./SadTalkerSettings";
import { LipsyncPageRequestSelectedModel } from "./LipsyncPageRequestSelectedModel";
import { RunSettings } from "./RunSettings";

export const LipsyncPageRequest: core.serialization.ObjectSchema<
    serializers.LipsyncPageRequest.Raw,
    Gooey.LipsyncPageRequest
> = core.serialization.object({
    functions: core.serialization.list(RecipeFunction).optional(),
    variables: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    inputFace: core.serialization.property("input_face", core.serialization.string().optional()),
    facePaddingTop: core.serialization.property("face_padding_top", core.serialization.number().optional()),
    facePaddingBottom: core.serialization.property("face_padding_bottom", core.serialization.number().optional()),
    facePaddingLeft: core.serialization.property("face_padding_left", core.serialization.number().optional()),
    facePaddingRight: core.serialization.property("face_padding_right", core.serialization.number().optional()),
    sadtalkerSettings: core.serialization.property("sadtalker_settings", SadTalkerSettings.optional()),
    selectedModel: core.serialization.property("selected_model", LipsyncPageRequestSelectedModel.optional()),
    inputAudio: core.serialization.property("input_audio", core.serialization.string().optional()),
    settings: RunSettings.optional(),
});

export declare namespace LipsyncPageRequest {
    interface Raw {
        functions?: RecipeFunction.Raw[] | null;
        variables?: Record<string, unknown> | null;
        input_face?: string | null;
        face_padding_top?: number | null;
        face_padding_bottom?: number | null;
        face_padding_left?: number | null;
        face_padding_right?: number | null;
        sadtalker_settings?: SadTalkerSettings.Raw | null;
        selected_model?: LipsyncPageRequestSelectedModel.Raw | null;
        input_audio?: string | null;
        settings?: RunSettings.Raw | null;
    }
}
