/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const LlmRequestResponseFormatType: core.serialization.Schema<
    serializers.LlmRequestResponseFormatType.Raw,
    Gooey.LlmRequestResponseFormatType
> = core.serialization.enum_(["text", "json_object"]);

export declare namespace LlmRequestResponseFormatType {
    type Raw = "text" | "json_object";
}
