/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const LlmTools: core.serialization.Schema<serializers.LlmTools.Raw, Gooey.LlmTools> =
    core.serialization.stringLiteral("json_to_pdf");

export declare namespace LlmTools {
    type Raw = "json_to_pdf";
}
