/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { PortraitRequestFunctionsItemTrigger } from "./PortraitRequestFunctionsItemTrigger";

export const PortraitRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.PortraitRequestFunctionsItem.Raw,
    Gooey.PortraitRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: PortraitRequestFunctionsItemTrigger,
});

export declare namespace PortraitRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: PortraitRequestFunctionsItemTrigger.Raw;
    }
}
