/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const PostV3RelatedQnaMakerDocAsyncFormRequestCitationStyle: core.serialization.Schema<
    serializers.PostV3RelatedQnaMakerDocAsyncFormRequestCitationStyle.Raw,
    Gooey.PostV3RelatedQnaMakerDocAsyncFormRequestCitationStyle
> = core.serialization.enum_([
    "number",
    "title",
    "url",
    "symbol",
    "markdown",
    "html",
    "slack_mrkdwn",
    "plaintext",
    "number_markdown",
    "number_html",
    "number_slack_mrkdwn",
    "number_plaintext",
    "symbol_markdown",
    "symbol_html",
    "symbol_slack_mrkdwn",
    "symbol_plaintext",
]);

export declare namespace PostV3RelatedQnaMakerDocAsyncFormRequestCitationStyle {
    type Raw =
        | "number"
        | "title"
        | "url"
        | "symbol"
        | "markdown"
        | "html"
        | "slack_mrkdwn"
        | "plaintext"
        | "number_markdown"
        | "number_html"
        | "number_slack_mrkdwn"
        | "number_plaintext"
        | "symbol_markdown"
        | "symbol_html"
        | "symbol_slack_mrkdwn"
        | "symbol_plaintext";
}
