/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const PostV3TextToSpeechAsyncFormRequestOpenaiTtsModel: core.serialization.Schema<
    serializers.PostV3TextToSpeechAsyncFormRequestOpenaiTtsModel.Raw,
    Gooey.PostV3TextToSpeechAsyncFormRequestOpenaiTtsModel
> = core.serialization.enum_(["tts_1", "tts_1_hd"]);

export declare namespace PostV3TextToSpeechAsyncFormRequestOpenaiTtsModel {
    type Raw = "tts_1" | "tts_1_hd";
}
