/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const PostV3CompareAiUpscalersAsyncFormRequestSelectedModelsItem: core.serialization.Schema<
    serializers.PostV3CompareAiUpscalersAsyncFormRequestSelectedModelsItem.Raw,
    Gooey.PostV3CompareAiUpscalersAsyncFormRequestSelectedModelsItem
> = core.serialization.enum_(["gfpgan_1_4", "real_esrgan_x2", "sd_x4", "real_esrgan", "gfpgan"]);

export declare namespace PostV3CompareAiUpscalersAsyncFormRequestSelectedModelsItem {
    type Raw = "gfpgan_1_4" | "real_esrgan_x2" | "sd_x4" | "real_esrgan" | "gfpgan";
}
