/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const PostV3TranslateAsyncFormRequestSelectedModel: core.serialization.Schema<
    serializers.PostV3TranslateAsyncFormRequestSelectedModel.Raw,
    Gooey.PostV3TranslateAsyncFormRequestSelectedModel
> = core.serialization.enum_(["google", "ghana_nlp"]);

export declare namespace PostV3TranslateAsyncFormRequestSelectedModel {
    type Raw = "google" | "ghana_nlp";
}
