/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const PostV3AsrAsyncFormRequestTranslationModel: core.serialization.Schema<
    serializers.PostV3AsrAsyncFormRequestTranslationModel.Raw,
    Gooey.PostV3AsrAsyncFormRequestTranslationModel
> = core.serialization.enum_(["google", "ghana_nlp"]);

export declare namespace PostV3AsrAsyncFormRequestTranslationModel {
    type Raw = "google" | "ghana_nlp";
}
