/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const PostV3VideoBotsAsyncFormRequestOpenaiTtsModel: core.serialization.Schema<
    serializers.PostV3VideoBotsAsyncFormRequestOpenaiTtsModel.Raw,
    Gooey.PostV3VideoBotsAsyncFormRequestOpenaiTtsModel
> = core.serialization.enum_(["tts_1", "tts_1_hd"]);

export declare namespace PostV3VideoBotsAsyncFormRequestOpenaiTtsModel {
    type Raw = "tts_1" | "tts_1_hd";
}
