/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const PostV3DeforumSdAsyncFormRequestSelectedModel: core.serialization.Schema<
    serializers.PostV3DeforumSdAsyncFormRequestSelectedModel.Raw,
    Gooey.PostV3DeforumSdAsyncFormRequestSelectedModel
> = core.serialization.enum_(["protogen_2_2", "epicdream"]);

export declare namespace PostV3DeforumSdAsyncFormRequestSelectedModel {
    type Raw = "protogen_2_2" | "epicdream";
}
