/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const PostV3RelatedQnaMakerDocAsyncFormRequestKeywordQuery: core.serialization.Schema<
    serializers.PostV3RelatedQnaMakerDocAsyncFormRequestKeywordQuery.Raw,
    Gooey.PostV3RelatedQnaMakerDocAsyncFormRequestKeywordQuery
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace PostV3RelatedQnaMakerDocAsyncFormRequestKeywordQuery {
    type Raw = string | string[];
}
