/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const PostV3VideoBotsAsyncFormRequestOpenaiVoiceName: core.serialization.Schema<
    serializers.PostV3VideoBotsAsyncFormRequestOpenaiVoiceName.Raw,
    Gooey.PostV3VideoBotsAsyncFormRequestOpenaiVoiceName
> = core.serialization.enum_(["alloy", "echo", "fable", "onyx", "nova", "shimmer"]);

export declare namespace PostV3VideoBotsAsyncFormRequestOpenaiVoiceName {
    type Raw = "alloy" | "echo" | "fable" | "onyx" | "nova" | "shimmer";
}
