/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const PostV3EmailFaceInpaintingAsyncFormRequestSelectedModel: core.serialization.Schema<
    serializers.PostV3EmailFaceInpaintingAsyncFormRequestSelectedModel.Raw,
    Gooey.PostV3EmailFaceInpaintingAsyncFormRequestSelectedModel
> = core.serialization.enum_(["sd_2", "runway_ml", "dall_e", "jack_qiao"]);

export declare namespace PostV3EmailFaceInpaintingAsyncFormRequestSelectedModel {
    type Raw = "sd_2" | "runway_ml" | "dall_e" | "jack_qiao";
}
