/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const PostV3RelatedQnaMakerDocAsyncFormRequestResponseFormatType: core.serialization.Schema<
    serializers.PostV3RelatedQnaMakerDocAsyncFormRequestResponseFormatType.Raw,
    Gooey.PostV3RelatedQnaMakerDocAsyncFormRequestResponseFormatType
> = core.serialization.enum_(["text", "json_object"]);

export declare namespace PostV3RelatedQnaMakerDocAsyncFormRequestResponseFormatType {
    type Raw = "text" | "json_object";
}
