/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const QrCodeRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.QrCodeRequestFunctionsItemTrigger.Raw,
    Gooey.QrCodeRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace QrCodeRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
