/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const RagRequestResponseFormatType: core.serialization.Schema<
    serializers.RagRequestResponseFormatType.Raw,
    Gooey.RagRequestResponseFormatType
> = core.serialization.enum_(["text", "json_object"]);

export declare namespace RagRequestResponseFormatType {
    type Raw = "text" | "json_object";
}
