/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const RelatedQnAPageRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.RelatedQnAPageRequestFunctionsItemTrigger.Raw,
    Gooey.RelatedQnAPageRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace RelatedQnAPageRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
