/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { RelatedDocSearchResponse } from "./RelatedDocSearchResponse";
import { CalledFunctionResponse } from "./CalledFunctionResponse";

export const RelatedQnADocPageOutput: core.serialization.ObjectSchema<
    serializers.RelatedQnADocPageOutput.Raw,
    Gooey.RelatedQnADocPageOutput
> = core.serialization.object({
    outputQueries: core.serialization.property("output_queries", core.serialization.list(RelatedDocSearchResponse)),
    serpResults: core.serialization.property(
        "serp_results",
        core.serialization.record(core.serialization.string(), core.serialization.unknown())
    ),
    calledFunctions: core.serialization.property(
        "called_functions",
        core.serialization.list(CalledFunctionResponse).optional()
    ),
});

export declare namespace RelatedQnADocPageOutput {
    interface Raw {
        output_queries: RelatedDocSearchResponse.Raw[];
        serp_results: Record<string, unknown>;
        called_functions?: CalledFunctionResponse.Raw[] | null;
    }
}
