/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { RelatedQnAPageRequestFunctionsItemTrigger } from "./RelatedQnAPageRequestFunctionsItemTrigger";

export const RelatedQnAPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.RelatedQnAPageRequestFunctionsItem.Raw,
    Gooey.RelatedQnAPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: RelatedQnAPageRequestFunctionsItemTrigger,
});

export declare namespace RelatedQnAPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: RelatedQnAPageRequestFunctionsItemTrigger.Raw;
    }
}
