/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const RemoveBackgroundRequestSelectedModel: core.serialization.Schema<
    serializers.RemoveBackgroundRequestSelectedModel.Raw,
    Gooey.RemoveBackgroundRequestSelectedModel
> = core.serialization.enum_(["dis", "u2net"]);

export declare namespace RemoveBackgroundRequestSelectedModel {
    type Raw = "dis" | "u2net";
}
