/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { ConversationEntry } from "./ConversationEntry";

export const ResponseModelFinalPrompt: core.serialization.Schema<
    serializers.ResponseModelFinalPrompt.Raw,
    Gooey.ResponseModelFinalPrompt
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.list(ConversationEntry)]);

export declare namespace ResponseModelFinalPrompt {
    type Raw = string | ConversationEntry.Raw[];
}
