/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { RunSettingsRetentionPolicy } from "./RunSettingsRetentionPolicy";

export const RunSettings: core.serialization.ObjectSchema<serializers.RunSettings.Raw, Gooey.RunSettings> =
    core.serialization.object({
        retentionPolicy: core.serialization.property("retention_policy", RunSettingsRetentionPolicy.optional()),
    });

export declare namespace RunSettings {
    interface Raw {
        retention_policy?: RunSettingsRetentionPolicy.Raw | null;
    }
}
