/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const SadTalkerSettingsPreprocess: core.serialization.Schema<
    serializers.SadTalkerSettingsPreprocess.Raw,
    Gooey.SadTalkerSettingsPreprocess
> = core.serialization.enum_(["crop", "extcrop", "resize", "full", "extfull"]);

export declare namespace SadTalkerSettingsPreprocess {
    type Raw = "crop" | "extcrop" | "resize" | "full" | "extfull";
}
