/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const Scheduler: core.serialization.Schema<serializers.Scheduler.Raw, Gooey.Scheduler> =
    core.serialization.enum_([
        "singlestep_dpm_solver",
        "multistep_dpm_solver",
        "dpm_sde",
        "dpm_discrete",
        "dpm_discrete_ancestral",
        "unipc",
        "lms_discrete",
        "heun",
        "euler",
        "euler_ancestral",
        "pndm",
        "ddpm",
        "ddim",
        "deis",
    ]);

export declare namespace Scheduler {
    type Raw =
        | "singlestep_dpm_solver"
        | "multistep_dpm_solver"
        | "dpm_sde"
        | "dpm_discrete"
        | "dpm_discrete_ancestral"
        | "unipc"
        | "lms_discrete"
        | "heun"
        | "euler"
        | "euler_ancestral"
        | "pndm"
        | "ddpm"
        | "ddim"
        | "deis";
}
