/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const SeoContentRequestResponseFormatType: core.serialization.Schema<
    serializers.SeoContentRequestResponseFormatType.Raw,
    Gooey.SeoContentRequestResponseFormatType
> = core.serialization.enum_(["text", "json_object"]);

export declare namespace SeoContentRequestResponseFormatType {
    type Raw = "text" | "json_object";
}
