/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const SerpSearchType: core.serialization.Schema<serializers.SerpSearchType.Raw, Gooey.SerpSearchType> =
    core.serialization.enum_(["search", "images", "videos", "places", "news"]);

export declare namespace SerpSearchType {
    type Raw = "search" | "images" | "videos" | "places" | "news";
}
