/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const SocialLookupEmailPageRequestResponseFormatType: core.serialization.Schema<
    serializers.SocialLookupEmailPageRequestResponseFormatType.Raw,
    Gooey.SocialLookupEmailPageRequestResponseFormatType
> = core.serialization.enum_(["text", "json_object"]);

export declare namespace SocialLookupEmailPageRequestResponseFormatType {
    type Raw = "text" | "json_object";
}
