/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const SocialLookupEmailPageRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.SocialLookupEmailPageRequestFunctionsItemTrigger.Raw,
    Gooey.SocialLookupEmailPageRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace SocialLookupEmailPageRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
