/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { SocialLookupEmailPageOutput } from "./SocialLookupEmailPageOutput";

export const SocialLookupEmailPageResponse: core.serialization.ObjectSchema<
    serializers.SocialLookupEmailPageResponse.Raw,
    Gooey.SocialLookupEmailPageResponse
> = core.serialization.object({
    id: core.serialization.string(),
    url: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    output: SocialLookupEmailPageOutput,
});

export declare namespace SocialLookupEmailPageResponse {
    interface Raw {
        id: string;
        url: string;
        created_at: string;
        output: SocialLookupEmailPageOutput.Raw;
    }
}
