/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { RecipeFunction } from "./RecipeFunction";
import { SocialLookupEmailPageRequestSelectedModel } from "./SocialLookupEmailPageRequestSelectedModel";
import { SocialLookupEmailPageRequestResponseFormatType } from "./SocialLookupEmailPageRequestResponseFormatType";
import { RunSettings } from "./RunSettings";

export const SocialLookupEmailPageRequest: core.serialization.ObjectSchema<
    serializers.SocialLookupEmailPageRequest.Raw,
    Gooey.SocialLookupEmailPageRequest
> = core.serialization.object({
    functions: core.serialization.list(RecipeFunction).optional(),
    variables: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    emailAddress: core.serialization.property("email_address", core.serialization.string()),
    inputPrompt: core.serialization.property("input_prompt", core.serialization.string().optional()),
    selectedModel: core.serialization.property("selected_model", SocialLookupEmailPageRequestSelectedModel.optional()),
    avoidRepetition: core.serialization.property("avoid_repetition", core.serialization.boolean().optional()),
    numOutputs: core.serialization.property("num_outputs", core.serialization.number().optional()),
    quality: core.serialization.number().optional(),
    maxTokens: core.serialization.property("max_tokens", core.serialization.number().optional()),
    samplingTemperature: core.serialization.property("sampling_temperature", core.serialization.number().optional()),
    responseFormatType: core.serialization.property(
        "response_format_type",
        SocialLookupEmailPageRequestResponseFormatType.optional()
    ),
    settings: RunSettings.optional(),
});

export declare namespace SocialLookupEmailPageRequest {
    interface Raw {
        functions?: RecipeFunction.Raw[] | null;
        variables?: Record<string, unknown> | null;
        email_address: string;
        input_prompt?: string | null;
        selected_model?: SocialLookupEmailPageRequestSelectedModel.Raw | null;
        avoid_repetition?: boolean | null;
        num_outputs?: number | null;
        quality?: number | null;
        max_tokens?: number | null;
        sampling_temperature?: number | null;
        response_format_type?: SocialLookupEmailPageRequestResponseFormatType.Raw | null;
        settings?: RunSettings.Raw | null;
    }
}
