/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const SpeechRecognitionRequestOutputFormat: core.serialization.Schema<
    serializers.SpeechRecognitionRequestOutputFormat.Raw,
    Gooey.SpeechRecognitionRequestOutputFormat
> = core.serialization.enum_(["text", "json", "srt", "vtt"]);

export declare namespace SpeechRecognitionRequestOutputFormat {
    type Raw = "text" | "json" | "srt" | "vtt";
}
