/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const TextToSpeechRequestTtsProvider: core.serialization.Schema<
    serializers.TextToSpeechRequestTtsProvider.Raw,
    Gooey.TextToSpeechRequestTtsProvider
> = core.serialization.enum_(["GOOGLE_TTS", "ELEVEN_LABS", "UBERDUCK", "BARK", "AZURE_TTS", "OPEN_AI"]);

export declare namespace TextToSpeechRequestTtsProvider {
    type Raw = "GOOGLE_TTS" | "ELEVEN_LABS" | "UBERDUCK" | "BARK" | "AZURE_TTS" | "OPEN_AI";
}
