/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const Text2AudioPageRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.Text2AudioPageRequestFunctionsItemTrigger.Raw,
    Gooey.Text2AudioPageRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace Text2AudioPageRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
