/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const TextToSpeechPageRequestOpenaiVoiceName: core.serialization.Schema<
    serializers.TextToSpeechPageRequestOpenaiVoiceName.Raw,
    Gooey.TextToSpeechPageRequestOpenaiVoiceName
> = core.serialization.enum_(["alloy", "echo", "fable", "onyx", "nova", "shimmer"]);

export declare namespace TextToSpeechPageRequestOpenaiVoiceName {
    type Raw = "alloy" | "echo" | "fable" | "onyx" | "nova" | "shimmer";
}
