/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { RecipeFunction } from "./RecipeFunction";
import { RunSettings } from "./RunSettings";

export const Text2AudioPageRequest: core.serialization.ObjectSchema<
    serializers.Text2AudioPageRequest.Raw,
    Gooey.Text2AudioPageRequest
> = core.serialization.object({
    functions: core.serialization.list(RecipeFunction).optional(),
    variables: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    textPrompt: core.serialization.property("text_prompt", core.serialization.string()),
    negativePrompt: core.serialization.property("negative_prompt", core.serialization.string().optional()),
    durationSec: core.serialization.property("duration_sec", core.serialization.number().optional()),
    numOutputs: core.serialization.property("num_outputs", core.serialization.number().optional()),
    quality: core.serialization.number().optional(),
    guidanceScale: core.serialization.property("guidance_scale", core.serialization.number().optional()),
    seed: core.serialization.number().optional(),
    sd2Upscaling: core.serialization.property("sd_2_upscaling", core.serialization.boolean().optional()),
    selectedModels: core.serialization.property(
        "selected_models",
        core.serialization.list(core.serialization.stringLiteral("audio_ldm")).optional()
    ),
    settings: RunSettings.optional(),
});

export declare namespace Text2AudioPageRequest {
    interface Raw {
        functions?: RecipeFunction.Raw[] | null;
        variables?: Record<string, unknown> | null;
        text_prompt: string;
        negative_prompt?: string | null;
        duration_sec?: number | null;
        num_outputs?: number | null;
        quality?: number | null;
        guidance_scale?: number | null;
        seed?: number | null;
        sd_2_upscaling?: boolean | null;
        selected_models?: "audio_ldm"[] | null;
        settings?: RunSettings.Raw | null;
    }
}
