/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { Text2AudioPageRequestFunctionsItemTrigger } from "./Text2AudioPageRequestFunctionsItemTrigger";

export const Text2AudioPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.Text2AudioPageRequestFunctionsItem.Raw,
    Gooey.Text2AudioPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: Text2AudioPageRequestFunctionsItemTrigger,
});

export declare namespace Text2AudioPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: Text2AudioPageRequestFunctionsItemTrigger.Raw;
    }
}
