/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { TextToSpeechPageOutput } from "./TextToSpeechPageOutput";

export const TextToSpeechPageResponse: core.serialization.ObjectSchema<
    serializers.TextToSpeechPageResponse.Raw,
    Gooey.TextToSpeechPageResponse
> = core.serialization.object({
    id: core.serialization.string(),
    url: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    output: TextToSpeechPageOutput,
});

export declare namespace TextToSpeechPageResponse {
    interface Raw {
        id: string;
        url: string;
        created_at: string;
        output: TextToSpeechPageOutput.Raw;
    }
}
