/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { TranslationPageRequestFunctionsItemTrigger } from "./TranslationPageRequestFunctionsItemTrigger";

export const TranslationPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.TranslationPageRequestFunctionsItem.Raw,
    Gooey.TranslationPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: TranslationPageRequestFunctionsItemTrigger,
});

export declare namespace TranslationPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: TranslationPageRequestFunctionsItemTrigger.Raw;
    }
}
