/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { RecipeFunction } from "./RecipeFunction";
import { TranslationPageRequestSelectedModel } from "./TranslationPageRequestSelectedModel";
import { RunSettings } from "./RunSettings";

export const TranslationPageRequest: core.serialization.ObjectSchema<
    serializers.TranslationPageRequest.Raw,
    Gooey.TranslationPageRequest
> = core.serialization.object({
    functions: core.serialization.list(RecipeFunction).optional(),
    variables: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    texts: core.serialization.list(core.serialization.string()).optional(),
    selectedModel: core.serialization.property("selected_model", TranslationPageRequestSelectedModel.optional()),
    translationSource: core.serialization.property("translation_source", core.serialization.string().optional()),
    translationTarget: core.serialization.property("translation_target", core.serialization.string().optional()),
    glossaryDocument: core.serialization.property("glossary_document", core.serialization.string().optional()),
    settings: RunSettings.optional(),
});

export declare namespace TranslationPageRequest {
    interface Raw {
        functions?: RecipeFunction.Raw[] | null;
        variables?: Record<string, unknown> | null;
        texts?: string[] | null;
        selected_model?: TranslationPageRequestSelectedModel.Raw | null;
        translation_source?: string | null;
        translation_target?: string | null;
        glossary_document?: string | null;
        settings?: RunSettings.Raw | null;
    }
}
