/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const TranslateRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.TranslateRequestFunctionsItemTrigger.Raw,
    Gooey.TranslateRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace TranslateRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
