/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { TranslateRequestFunctionsItemTrigger } from "./TranslateRequestFunctionsItemTrigger";

export const TranslateRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.TranslateRequestFunctionsItem.Raw,
    Gooey.TranslateRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: TranslateRequestFunctionsItemTrigger,
});

export declare namespace TranslateRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: TranslateRequestFunctionsItemTrigger.Raw;
    }
}
