/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const UpscaleRequestFunctionsItemTrigger: core.serialization.Schema<
    serializers.UpscaleRequestFunctionsItemTrigger.Raw,
    Gooey.UpscaleRequestFunctionsItemTrigger
> = core.serialization.enum_(["pre", "post"]);

export declare namespace UpscaleRequestFunctionsItemTrigger {
    type Raw = "pre" | "post";
}
