/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { VideoBotsPageRequestMessagesItemRole } from "./VideoBotsPageRequestMessagesItemRole";
import { VideoBotsPageRequestMessagesItemContent } from "./VideoBotsPageRequestMessagesItemContent";

export const VideoBotsPageRequestMessagesItem: core.serialization.ObjectSchema<
    serializers.VideoBotsPageRequestMessagesItem.Raw,
    Gooey.VideoBotsPageRequestMessagesItem
> = core.serialization.object({
    role: VideoBotsPageRequestMessagesItemRole,
    content: VideoBotsPageRequestMessagesItemContent,
    displayName: core.serialization.property("display_name", core.serialization.string().optional()),
});

export declare namespace VideoBotsPageRequestMessagesItem {
    interface Raw {
        role: VideoBotsPageRequestMessagesItemRole.Raw;
        content: VideoBotsPageRequestMessagesItemContent.Raw;
        display_name?: string | null;
    }
}
