/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { ChatCompletionContentPartTextParam } from "./ChatCompletionContentPartTextParam";
import { ChatCompletionContentPartImageParam } from "./ChatCompletionContentPartImageParam";

export const VideoBotsPageRequestMessagesItemContentItem: core.serialization.Schema<
    serializers.VideoBotsPageRequestMessagesItemContentItem.Raw,
    Gooey.VideoBotsPageRequestMessagesItemContentItem
> = core.serialization
    .union("type", {
        text: ChatCompletionContentPartTextParam,
        image_url: ChatCompletionContentPartImageParam,
    })
    .transform<Gooey.VideoBotsPageRequestMessagesItemContentItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace VideoBotsPageRequestMessagesItemContentItem {
    type Raw = VideoBotsPageRequestMessagesItemContentItem.Text | VideoBotsPageRequestMessagesItemContentItem.ImageUrl;

    interface Text extends ChatCompletionContentPartTextParam.Raw {
        type: "text";
    }

    interface ImageUrl extends ChatCompletionContentPartImageParam.Raw {
        type: "image_url";
    }
}
