/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";
import { VideoBotsPageRequestFunctionsItemTrigger } from "./VideoBotsPageRequestFunctionsItemTrigger";

export const VideoBotsPageRequestFunctionsItem: core.serialization.ObjectSchema<
    serializers.VideoBotsPageRequestFunctionsItem.Raw,
    Gooey.VideoBotsPageRequestFunctionsItem
> = core.serialization.object({
    url: core.serialization.string(),
    trigger: VideoBotsPageRequestFunctionsItemTrigger,
});

export declare namespace VideoBotsPageRequestFunctionsItem {
    interface Raw {
        url: string;
        trigger: VideoBotsPageRequestFunctionsItemTrigger.Raw;
    }
}
