/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Gooey from "../../api/index";
import * as core from "../../core";

export const WebSearchLlmRequestResponseFormatType: core.serialization.Schema<
    serializers.WebSearchLlmRequestResponseFormatType.Raw,
    Gooey.WebSearchLlmRequestResponseFormatType
> = core.serialization.enum_(["text", "json_object"]);

export declare namespace WebSearchLlmRequestResponseFormatType {
    type Raw = "text" | "json_object";
}
