/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Gooey from "../../../../../api/index";
import * as core from "../../../../../core";
import { RecipeFunction } from "../../../../types/RecipeFunction";
import { CompareLlmPageRequestSelectedModelsItem } from "../../types/CompareLlmPageRequestSelectedModelsItem";
import { CompareLlmPageRequestResponseFormatType } from "../../types/CompareLlmPageRequestResponseFormatType";
import { RunSettings } from "../../../../types/RunSettings";

export const CompareLlmPageRequest: core.serialization.Schema<
    serializers.CompareLlmPageRequest.Raw,
    Omit<Gooey.CompareLlmPageRequest, "exampleId">
> = core.serialization.object({
    functions: core.serialization.list(RecipeFunction).optional(),
    variables: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    inputPrompt: core.serialization.property("input_prompt", core.serialization.string().optional()),
    selectedModels: core.serialization.property(
        "selected_models",
        core.serialization.list(CompareLlmPageRequestSelectedModelsItem).optional()
    ),
    avoidRepetition: core.serialization.property("avoid_repetition", core.serialization.boolean().optional()),
    numOutputs: core.serialization.property("num_outputs", core.serialization.number().optional()),
    quality: core.serialization.number().optional(),
    maxTokens: core.serialization.property("max_tokens", core.serialization.number().optional()),
    samplingTemperature: core.serialization.property("sampling_temperature", core.serialization.number().optional()),
    responseFormatType: core.serialization.property(
        "response_format_type",
        CompareLlmPageRequestResponseFormatType.optional()
    ),
    settings: RunSettings.optional(),
});

export declare namespace CompareLlmPageRequest {
    interface Raw {
        functions?: RecipeFunction.Raw[] | null;
        variables?: Record<string, unknown> | null;
        input_prompt?: string | null;
        selected_models?: CompareLlmPageRequestSelectedModelsItem.Raw[] | null;
        avoid_repetition?: boolean | null;
        num_outputs?: number | null;
        quality?: number | null;
        max_tokens?: number | null;
        sampling_temperature?: number | null;
        response_format_type?: CompareLlmPageRequestResponseFormatType.Raw | null;
        settings?: RunSettings.Raw | null;
    }
}
