/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Gooey from "../../../../index";

/**
 * @example
 *     {
 *         integrationId: "integration_id"
 *     }
 */
export interface CreateStreamRequest {
    /** Your Integration ID as shown in the Copilot Integrations tab */
    integrationId: string;
    /**
     * The gooey conversation ID.
     *
     * If not provided, a new conversation will be started and a new ID will be returned in the response. Use this to maintain the state of the conversation between requests.
     *
     * Note that you may not provide a custom ID here, and must only use the `conversation_id` returned in a previous response.
     */
    conversationId?: string;
    /**
     * Your app's custom user ID.
     *
     * If not provided, a random user will be created and a new ID will be returned in the response. If a `conversation_id` is provided, this field is automatically set to the user's id associated with that conversation.
     */
    userId?: string;
    /**
     * Your app's custom message ID for the user message.
     *
     * If not provided, a random ID will be generated and returned in the response. This is useful for tracking messages in the conversation.
     */
    userMessageId?: string;
    /** The button that was pressed by the user. */
    buttonPressed?: Gooey.ButtonPressed;
    functions?: Gooey.RecipeFunction[];
    /** Variables to be used as Jinja prompt templates and in functions as arguments */
    variables?: Record<string, unknown>;
    inputPrompt?: string;
    inputAudio?: string;
    inputImages?: string[];
    inputDocuments?: string[];
    /** Select a workflow to extract text from documents and images. */
    docExtractUrl?: string;
    messages?: Gooey.ConversationEntry[];
    botScript?: string;
    selectedModel?: Gooey.CreateStreamRequestSelectedModel;
    /** When your copilot users upload a photo or pdf, what kind of document are they mostly likely to upload? (via [Azure](https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/how-to-guides/use-sdk-rest-api?view=doc-intel-3.1.0&tabs=linux&pivots=programming-language-rest-api)) */
    documentModel?: string;
    avoidRepetition?: boolean;
    numOutputs?: number;
    quality?: number;
    maxTokens?: number;
    samplingTemperature?: number;
    taskInstructions?: string;
    queryInstructions?: string;
    keywordInstructions?: string;
    documents?: string[];
    maxReferences?: number;
    maxContextWords?: number;
    scrollJump?: number;
    embeddingModel?: Gooey.CreateStreamRequestEmbeddingModel;
    /**
     * Weightage for dense vs sparse embeddings. `0` for sparse, `1` for dense, `0.5` for equal weight.
     * Generally speaking, dense embeddings excel at understanding the context of the query, whereas sparse vectors excel at keyword matches.
     *
     */
    denseWeight?: number;
    citationStyle?: Gooey.CreateStreamRequestCitationStyle;
    useUrlShortener?: boolean;
    /** Choose a model to transcribe incoming audio messages to text. */
    asrModel?: Gooey.CreateStreamRequestAsrModel;
    /** Choose a language to transcribe incoming audio messages to text. */
    asrLanguage?: string;
    translationModel?: Gooey.CreateStreamRequestTranslationModel;
    /** Choose a language to translate incoming text & audio messages to English and responses back to your selected language. Useful for low-resource languages. */
    userLanguage?: string;
    /**
     * Translation Glossary for User Langauge -> LLM Language (English)
     *
     */
    inputGlossaryDocument?: string;
    /**
     * Translation Glossary for LLM Language (English) -> User Langauge
     *
     */
    outputGlossaryDocument?: string;
    lipsyncModel?: Gooey.CreateStreamRequestLipsyncModel;
    /** Give your copilot superpowers by giving it access to tools. Powered by [Function calling](https://platform.openai.com/docs/guides/function-calling). */
    tools?: Gooey.LlmTools[];
    ttsProvider?: Gooey.CreateStreamRequestTtsProvider;
    uberduckVoiceName?: string;
    uberduckSpeakingRate?: number;
    googleVoiceName?: string;
    googleSpeakingRate?: number;
    googlePitch?: number;
    barkHistoryPrompt?: string;
    /** Use `elevenlabs_voice_id` instead */
    elevenlabsVoiceName?: string;
    elevenlabsApiKey?: string;
    elevenlabsVoiceId?: string;
    elevenlabsModel?: string;
    elevenlabsStability?: number;
    elevenlabsSimilarityBoost?: number;
    elevenlabsStyle?: number;
    elevenlabsSpeakerBoost?: boolean;
    azureVoiceName?: string;
    openaiVoiceName?: Gooey.CreateStreamRequestOpenaiVoiceName;
    openaiTtsModel?: Gooey.CreateStreamRequestOpenaiTtsModel;
    inputFace?: string;
    facePaddingTop?: number;
    facePaddingBottom?: number;
    facePaddingLeft?: number;
    facePaddingRight?: number;
    sadtalkerSettings?: Gooey.SadTalkerSettings;
    /** Use `input_prompt` instead */
    inputText?: string;
}
