/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const AsyncFormSmartGptRequestResponseFormatType: core.serialization.Schema<
    serializers.AsyncFormSmartGptRequestResponseFormatType.Raw,
    Gooey.AsyncFormSmartGptRequestResponseFormatType
> = core.serialization.enum_(["text", "json_object"]);

export declare namespace AsyncFormSmartGptRequestResponseFormatType {
    type Raw = "text" | "json_object";
}
