/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";
import { CopilotCompletionRequestMessagesItemRole } from "./CopilotCompletionRequestMessagesItemRole";
import { CopilotCompletionRequestMessagesItemContent } from "./CopilotCompletionRequestMessagesItemContent";

export const CopilotCompletionRequestMessagesItem: core.serialization.ObjectSchema<
    serializers.CopilotCompletionRequestMessagesItem.Raw,
    Gooey.CopilotCompletionRequestMessagesItem
> = core.serialization.object({
    role: CopilotCompletionRequestMessagesItemRole,
    content: CopilotCompletionRequestMessagesItemContent,
    displayName: core.serialization.property("display_name", core.serialization.string().optional()),
});

export declare namespace CopilotCompletionRequestMessagesItem {
    interface Raw {
        role: CopilotCompletionRequestMessagesItemRole.Raw;
        content: CopilotCompletionRequestMessagesItemContent.Raw;
        display_name?: string | null;
    }
}
