/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const CopilotCompletionRequestSadtalkerSettingsPreprocess: core.serialization.Schema<
    serializers.CopilotCompletionRequestSadtalkerSettingsPreprocess.Raw,
    Gooey.CopilotCompletionRequestSadtalkerSettingsPreprocess
> = core.serialization.enum_(["crop", "extcrop", "resize", "full", "extfull"]);

export declare namespace CopilotCompletionRequestSadtalkerSettingsPreprocess {
    type Raw = "crop" | "extcrop" | "resize" | "full" | "extfull";
}
