/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const CopilotCompletionRequestLipsyncModel: core.serialization.Schema<
    serializers.CopilotCompletionRequestLipsyncModel.Raw,
    Gooey.CopilotCompletionRequestLipsyncModel
> = core.serialization.enum_(["Wav2Lip", "SadTalker"]);

export declare namespace CopilotCompletionRequestLipsyncModel {
    type Raw = "Wav2Lip" | "SadTalker";
}
