/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const CopilotCompletionRequestTranslationModel: core.serialization.Schema<
    serializers.CopilotCompletionRequestTranslationModel.Raw,
    Gooey.CopilotCompletionRequestTranslationModel
> = core.serialization.enum_(["google", "ghana_nlp"]);

export declare namespace CopilotCompletionRequestTranslationModel {
    type Raw = "google" | "ghana_nlp";
}
