/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const CopilotCompletionRequestOpenaiTtsModel: core.serialization.Schema<
    serializers.CopilotCompletionRequestOpenaiTtsModel.Raw,
    Gooey.CopilotCompletionRequestOpenaiTtsModel
> = core.serialization.enum_(["tts_1", "tts_1_hd"]);

export declare namespace CopilotCompletionRequestOpenaiTtsModel {
    type Raw = "tts_1" | "tts_1_hd";
}
