/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Gooey from "../../../../api/index";
import * as core from "../../../../core";

export const CopilotCompletionRequestOpenaiVoiceName: core.serialization.Schema<
    serializers.CopilotCompletionRequestOpenaiVoiceName.Raw,
    Gooey.CopilotCompletionRequestOpenaiVoiceName
> = core.serialization.enum_(["alloy", "echo", "fable", "onyx", "nova", "shimmer"]);

export declare namespace CopilotCompletionRequestOpenaiVoiceName {
    type Raw = "alloy" | "echo" | "fable" | "onyx" | "nova" | "shimmer";
}
