/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const GooeyEnvironment = {
    Default: "https://api.gooey.ai",
} as const;

export type GooeyEnvironment = typeof GooeyEnvironment.Default;
